### PR TITLE
Add `NOECHOE` and `TEST_L` to the list of `SHOPT` options

### PR DESCRIPTION
**Pull request by JohnoKing**
src/cmd/ksh93/SHOPT.sh:
- Add the `SHOPT_ECHOE` and `SHOPT_TEST_L` compile time options to the list of `SHOPT` options (set to probe by default).

src/cmd/ksh93/features/options:
- Small bugfix: Allow `SHOPT_TEST_L` to be manually enabled on systems that don't support `$(whence -p test) -l /foo`.
- Add a comment describing the `SHOPT_MULTIBYTE` feature test and separate it from the `SHOPT_DEVFD` test.

### CODE REVIEW

**Comment by McDutchie** [comment]
I don't think `SHOPT_ECHOE` and `SHOPT_TEST_L` were meant to be enabled manually, but I don't object to changing that.

Although I do wonder on what system `SHOPT_TEST_L` is relevant -- I don't know of any where `/bin/test` has that option.

**Comment by McDutchie** [comment]
There is no probe for `SHOPT_ECHOE` so I think it's better to list it as off (0) by default.

It's also misleadingly named, as it turns off `echo -e` instead of turning it on.

The only mention of `SHOPT_ECHOE` in Google results links to https://github.com/att/ast/issues/370 which is interesting reading.

Since it was an unlisted option and has barely any public mention, do you think it would be okay to rename it to `SHOPT_NOECHOE`?

**Comment by JohnoKing** [comment]
Those changes sound sensible. I've pushed a new commit with the suggested changes.

**Comment by JohnoKing** [comment]
For posterity, I've found out after enough digging IRIX's `test` command supports `-l`, so `SHOPT_TEST_L` was presumably meant for use with IRIX scripts. I can't find anything else that accepts that flag.

**Comment by McDutchie** [comment]
Thanks for that information. The last IRIX was released nearly twenty years ago, so I'll delete SHOPT_TEST_L from the dev branch (it can stay on 1.0.x).

**Pull request merged**
