### PR TITLE
Fix how the bell character is handled after `SIGWINCH`

### PR DESCRIPTION
**Pull request by JohnoKing**
To set the terminal's window title in bash and zsh, the `$PS1` prompt can be set with the title placed between `$'\E]0;'` and `$'\a'`. This also works in ksh unless the shell receives `SIGWINCH`:

```sh
$ cat ./set-window-title
set +b
set -o emacs    # Or vi mode
typeset -A fmt=(
	[start_title]=$'\E]0;'
	[end_title]=$'\a'
)
unset -f PS1.get
PS1="${fmt[start_title]}$(hostname): $(uname)${fmt[end_title]}\$ "

$ source ./set-window-title
$ (sleep .1; kill -WINCH $$) &
```

With a `$PS1` that sets a window title, the shell prompt breaks until two interrupts are received. This is caused by `ed_setup()` skipping `$'\a'` (the bell character), so the fix is to avoid skipping it when handling `SIGWINCH`. For this fix to have any effect, `shp->winch` is set only back to zero after `sfpkrd()`.

### CODE REVIEW

**Comment by posguy99** [comment]
Is this what the reproducer is supposed to do without the patch?  All I had to do was hit `RETURN`.
```
$ source ./set-window-title 
$ (sleep .1; kill -WINCH $$) &
[1]	1304
$ 
[1] +  Done                    (sleep .1; kill -WINCH $$) &

0;mbp13.local: Darwin$ 
$ 
```

**Comment by JohnoKing** [comment]
I forgot to include `set +b` in the reproducer. Try it now.

**Comment by posguy99** [comment]
```
$ cat ./set-window-title 
set -o emacs    # Or vi mode
set +b
typeset -A fmt=(
	[start_title]=$'\E]0;'
	[end_title]=$'\a'
)
PS1="${fmt[start_title]}$(hostname): $(uname)${fmt[end_title]}\$ "
$ 
$ source ./set-window-title 
$ (sleep .1; kill -WINCH $$) &
[1]	1476
$      <-- this ends up with the cursor sitting on it

0;mbp13.local: Darwin$      <-- hit RETURN, get this line
$      <-- hit RETURN again, get this line
```

Is that what it should do now?  Def a broken thing. :)

**Comment by JohnoKing** [comment]
That's the bug (I'll note on my system the reproducer corrupts the window title). After applying my bugfix the output should look like this:
```
$ source ./set-window-title
$ (sleep 1; kill -WINCH $$) &
[1]	9791
$  <-- hit RETURN
[1] +  Done                    (sleep 1; kill -WINCH $$) &
$  <-- hit RETURN
$
```

**Comment by McDutchie** [comment]
The fix appears to work, but I don't understand it.

The `ed_setup()` function is called every time you press Return for a new prompt. So if the `case '\a': break` on line 725 really cut out `\a` characters from the prompt, then that prompt should always break. But it doesn't. It only breaks upon receiving SIGWINCH. So that code apparently does not print the prompt. If my reading of it is correct, what it actually does is calculate how many screen character positions the prompt occupies. And skipping the bell character would make sense for that, as it does not occupy a screen position.

I tried restoring the original `break` while keeping the rest of the patch. My own testing shows that the second part of the patch (moving the `shp->winch = 0;` assignment) is sufficient to fix the bug. Can you confirm?

Why that fixes it, I've no idea. But I want to find out before merging this, otherwise we cannot accurately document the fix.

**Comment by JohnoKing** [comment]
> I tried restoring the original break while keeping the rest of the patch. My own testing shows that the second part of the patch (moving the shp->winch = 0; assignment) is sufficient to fix the bug. Can you confirm?

Confirmed. I'm not sure why that alone is enough to fix it (deleting the `break` condition also works, which is why I put the `!shp->winch` if statement there).

**Comment by JohnoKing** [comment]
The "fix" works because it stops the `SIGWINCH` loop from repeating. With the patch below ksh will abort after receiving `SIGWINCH` because `sfpkrd` causes `shp->winch` to be set. `sfpkrd` is supposed to intercept `SIGWINCH`, which means the current fix isn't correct:
```diff
diff --git a/src/cmd/ksh93/edit/edit.c b/src/cmd/ksh93/edit/edit.c
index 372748c3..0a86ada6 100644
--- a/src/cmd/ksh93/edit/edit.c
+++ b/src/cmd/ksh93/edit/edit.c
@@ -912,8 +912,12 @@ int ed_read(void *context, int fd, char *buff, int size, int reedit)
 		/* an interrupt that should be ignored */
 		errno = 0;
 		if(!waitevent || (rv=(*waitevent)(fd,-1L,0))>=0)
+		{
+			shp->winch = 0;
 			rv = sfpkrd(fd,buff,size,delim,-1L,mode);
-		shp->winch = 0;
+			if(shp->winch)
+				abort();
+		}
 	}
 	if(rv < 0)
 	{
```

**Comment by McDutchie** [comment]
> (deleting the `break` condition also works, which is why I put the `!shp->winch` if statement there).

Confirmed. But why?

I tried both changes separately in an xterm window and tried changing its size. Turns out moving the `shp->winch = 0` assignment is not correct: SIGWINCH handling is disabled completely, the command line is no longer redrawn when resizing the window. (*edit:* you had noticed that by now, our messages crossed each other.)

I'm not convinced the change in '\a' handling is correct, either. It appears to work, but it makes no sense to me.

**Comment by JohnoKing** [comment]
After looking into this bug a bit more, I'm fairly certain the fix I've applied in commit 5b865828 is ~the~ a correct one. The linked commit removes these lines of code:
https://github.com/ksh93/ksh/blob/ca2443b58c35653986a66251b3fdc2dd63ed7864/src/cmd/ksh93/edit/edit.c#L715-L718
The singular `break` deletes the bell character `$'\a'` from the prompt. To verify this you can replace `\a` in the code above with a different character. In the example below `\a` has been replaced with `_`:
```sh
$ arch/*/bin/ksh
$ unset -f PS1.get; PS1='_\$_ '  # Set $PS1 prompt
_$_ set +b; (sleep .1; kill -WINCH $$) &
$ # After SIGWINCH the underscores are removed
```

This behavior is what causes the bug. To set the terminal's window title, the title itself must be placed in between `$'\E]0;'` and `$'\a'`, and the entire string must be printed (including `$'\a'`). As such `ed_setup()` has no business deleting the bell character from the prompt string.

To demonstrate the importance of `\a` in setting the window title, `printf` can be used to experiment:
```sh
$ unset -f PS1.get; PS1='$ '  # Reset $PS1
$ printf $'\E]0;'"Example Title"$'\a'
```
If you remove the ending `\a`, attempting to print a window title will cause behavior similar to the bug in ksh (since neither ksh nor the terminal know where the title ends).

**Comment by McDutchie** [comment]
Thanks for looking into it more. I've done some code and documentation reading myself now as well. It turns out that whole [code block](https://github.com/ksh93/ksh/blob/ca2443b58c35653986a66251b3fdc2dd63ed7864/src/cmd/ksh93/edit/edit.c#L657-L738) is in fact related to displaying the prompt, but it's not as simple as that. Normal prompt printing is handled in io.c by [`io_prompt()`](https://github.com/ksh93/ksh/blob/ca2443b58c35653986a66251b3fdc2dd63ed7864/src/cmd/ksh93/sh/io.c#L2074-L2151), whereas this entire [block](https://github.com/ksh93/ksh/blob/ca2443b58c35653986a66251b3fdc2dd63ed7864/src/cmd/ksh93/edit/edit.c#L657-L738) in `ed_setup()` is for filling an `e_prompt` buffer that is used later when the command line needs to be redrawn.

Contrary to the [comment](https://github.com/ksh93/ksh/blob/ca2443b58c35653986a66251b3fdc2dd63ed7864/src/cmd/ksh93/include/edit.h#L111) in edit.h, that buffer is not exactly for "the prompt" but for the parsed/expanded and length-counted part of the prompt that is relevant to redrawing the command line. So that buffer filling routine ignores everything before the last newline, because only the part of the prompt that immediately precedes the command line on the same line is relevant for that purpose.

So, that explains why the bug only occurs when the command line is redrawn (`SIGWINCH` is not the only condition where that happens, by the way). I haven't tried it, but one workaround should be to have a multiline prompt and set the xterm title in any line except the last.

This also explains why the original authors wanted to skip the bell character in the `e_prompt` buffer. If you have a bell character in your prompt, you expect it to beep whenever it prints the complete prompt, which is done with `io_prompt()` in io.c. You don't want it to beep again when the command line is redrawn for `SIGWINCH` or other reasons, because that's not printing a new prompt, it's just a refresh. So, while the current fix is correct as in fixing this bug, it also removes a feature that I don't think we want to remove.

I think a more correct fix would be for that code block to recognise and cut out sequences for setting the terminal title. The title will already have been set when the full prompt was printed by `io_prompt()`, so there's no need to set it again when redrawing the command line. This way, we can also keep the feature that avoids excessive beeps.

For more information, read the [Xterm Control Sequences](https://invisible-island.net/xterm/ctlseqs/ctlseqs.html) document. Among other things, it shows that these sequences can be terminated by either the legacy `BEL` (`\a`) or the recommended `ST` (`ESC` `\`) sequence, so the fix recognises both of those terminators. And there's another workaround: use the `ESC` `\` terminator instead.

~~I have a fix ready now, I'll push it after posting this comment. Please let me know if you find problems.~~ Sorry, need some more time to test.

**Comment by hyenias** [comment]
FYI: The following works to alter my terminal window title on all three of my macOS terminal clients (iTerm2, Terminal, Alacritty). I changed to using `print -n` instead of using `printf` as we are not providing a format string.
```ksh
$ print -n $'\E]0;''Example2 Title'$'\E\\'
```

**Comment by McDutchie** [comment]
I think I've worked out the kinks now. See commit above.

Hmm, maybe not. Under "Operating System Commands", [here](https://invisible-island.net/xterm/ctlseqs/ctlseqs.html), multiple-digit values between the `]` and the `;` are documented. This code only looks for single-digit values.

Still, this is probably good enough to start testing it while I work on fixing that.

**Comment by McDutchie** [comment]
That should be fixed now as well, please test…

**Comment by JohnoKing** [comment]
The current patch is working well for me. Regarding how escape sequences are handled in ksh, there is a ksh2020 patch that adds more escape sequence recognition: https://github.com/att/ast/issues/399. Maybe this could be worth integrating into ksh93u+m?

**Comment by hyenias** [comment]
Unfortunately, the current patch is not working correctly on my macOS or Ubuntu 18.04 when using option 2 (alt). It appears once the PS1 gets redefined all sorts of weird stuff happens such as missing first character and just a blinking cursor without a prompt. I am able to hit enter a couple of times then type `exit` to get out.

Option 1 (bell):
```ksh
typeset -A fmt=( [start_title]=$'\E]0;' [end_title]=$'\a' )
PS1="${fmt[start_title]}$(hostname): $(uname)${fmt[end_title]}\$ "

(sleep 1; kill -WINCH $$) &
```
Option 2 (alt using ESC \):
```ksh
typeset -A fmt=( [start_title]=$'\E]0;' [end_title]=$'\E\\' )
PS1="${fmt[start_title]}$(hostname): $(uname)${fmt[end_title]}\$ "

(sleep 1; kill -WINCH $$) &
```
Interactive Results:
```ksh
MacBook:~$ ksh
MacBook:~$ PS1='$ '
$ typeset -A fmt=( [start_title]=$'\E]0;' [end_title]=$'\E\\' )
$ PS1="${fmt[start_title]}$(hostname): $(uname)${fmt[end_title]}\$ "

leep 1; kill -WINCH $$) &
[1]	36377
0;MacBook.local: Darwin
1] +  Done                    (sleep 1; kill -WINCH $$) &


xit
MacBook:~$ 
```

**Comment by JohnoKing** [comment]
For option 2, `$PS1` expects `$'\E\\\\'`, not `$'\E\\'` (which differs from `print`, ~so that might be a bug~).

**Comment by hyenias** [comment]
Yep! You are correct. I had no idea of PS1's escaping needs. Option 2 works using the following.

Option 2 (alt using ESC):
```ksh
$ typeset -A fmt=( [start_title]=$'\E]0;' [end_title]=$'\E\\\\' )
$ PS1="${fmt[start_title]}$(hostname): $(uname)${fmt[end_title]}\$ "
$
$ (sleep 1; kill -WINCH $$) &
[1]	36730
$
[1] +  Done                    (sleep 1; kill -WINCH $$) &
$
```

**Comment by hyenias** [comment]
I am guessing what caused all of my weird behavior in my PS1 prompt was with the continuation character aka backslash. Or perhaps it was simply backslash escaping out the next character and/or its interpretation into some wrong terminal sequence.

**Comment by McDutchie** [comment]
The value of PS1 is "expanded for parameter expansion, command substitution, and  arithmetic substitution" (man page), which also removes one level of backslash escaping, e.g. `PS1='foo\\bar '` changes your prompt to `foo\bar`. C-style `$'`quoting`'` needs another level of backslash escaping, e.g. `'foo\\bar'` == `$'foo\\\\bar'`.

You can see why people continue to use the bell character as the terminator though it's been deprecated. A sequence containing a backslash is hard to use due to escaping headaches.

**Comment by McDutchie** [comment]
I am not sure about the change to `io_prompt()` that I backported from @perette's ksh2020 patch. I think it could theoretically (?) break compatibility with existing rc scripts that assume the need to escape '!' in escape sequences by changing it to '!!'. Thoughts/opinions?

**Comment by hyenias** [comment]
I have no direct insights into rc scripts. Not sure how we would become aware of such incompatibilities due to those workarounds until you break it and see who screams. As I am cautious, I would table the change for a future feature release or until new evidence indicates it corrects a bug.

**Comment by McDutchie** [comment]
I tend to agree with @hyenias. I'm also not sure that the io_prompt() changes are 100% correct. It only seems to check for a `!` that immediately follows `ESC` `[`, `ESC` `]` or `ESC` `(`. This makes `tput rs2` work without modification on terminals where the output of that includes the `ESC` `[` `!` `p` sequence, but a `!` might well appear later on in a different escape sequence. Probably best not to change this and instead document in the manual that escape sequences in `$PS1` need all `!` changing to `!!`.

**Pull request merged**
