### PR TITLE
exec: Don't exit after error in interactive shells

### PR DESCRIPTION
**Pull request by JohnoKing**
As of POSIX.1-2024, interactive shells are not allowed to exit when `exec` fails to run a command[*]. This commit amends ksh's `exec` implementation to comply with this requirement (in `path_exec()`).

[*]: https://pubs.opengroup.org/onlinepubs/9799919799/utilities/V3_chap02.html#tag_19_21

### CODE REVIEW

**Comment by McDutchie** [comment]
Thanks for the PR!

One problem:
```
$ exec nonexistent >/dev/null 2>&1
```
...and now you have a basically unusable shell: no prompt is displayed and nothing you type is echoed. You're operating blind.

This behaviour is actually specified by POSIX 2024: "If the [exec](https://pubs.opengroup.org/onlinepubs/9799919799/utilities/V3_chap02.html#exec) command fails and the shell does not exit, any redirections associated with the [exec](https://pubs.opengroup.org/onlinepubs/9799919799/utilities/V3_chap02.html#exec) command that were successfully made shall take effect in the current shell execution environment."

But I think that's worse than it was before; at least when you lost your shell you could log back in or reopen the terminal window, and you didn't have to operate blind. So I do wonder if this highly undesirable side effect in the case of a nonexistent comment was actually intended by the resolution of [Austin Group bug 1157](https://austingroupbugs.net/view.php?id=1157).

**Comment by posguy99** [comment]
Why does the spec say "If the exec command fails and the shell does not exit..."?  What's the point of the **and**?

`bash` (even the old macOS `bash`) hangs as you describe.  `mksh`, `oksh`, and `dash` (and `ksh`) exit back to the parent.  `yash` does something different:

```
mwilson@mbp-m2 ~ 2$ echo $YASH_VERSION
2.57
mwilson@mbp-m2 ~ 2$ exec nonexistent >/dev/null 2>&1
mwilson@mbp-m2 ~ 127 2$ 
```

It failed the `exec`, but it didn't exit back to the parent, and the redirects aren't in effect.

**Comment by McDutchie** [comment]
> Why does the spec say "If the exec command fails and the shell does not exit..."? What's the point of the **and**?

The point is that the shell, in the new 2024 spec, shall not exit on failure to execute the command if it is interactive. In other words, if it's non-interactive, it still exits.

None of this affects scripts, by the way, or even subshells of interactive shells. Nothing changes there compared to the old spec.

> `bash` (even the old macOS `bash`) hangs as you describe.

It doesn't hang though, it just doesn't show any output. You can blindly type something (e.g. `exit`) and it will be executed.

Still, I think this is clearly broken, it's not something I am willing to subject users to, and I will file an Austin Group bug about it. When a user does 'exec cmd >file', they expect the shell to be replaced by `cmd` with the redirection to `file` in effect. But if `cmd` cannot be executed and the shell is not replaced, then it makes no sense for the redirection to persist, because it was intended for `cmd` only.

> `mksh`, `oksh`, and `dash` (and `ksh`) exit back to the parent.

They are still acting according to the pre-2024 spec.

> `yash` does something different:
> 
> ```
> mwilson@mbp-m2 ~ 2$ echo $YASH_VERSION
> 2.57
> mwilson@mbp-m2 ~ 2$ exec nonexistent >/dev/null 2>&1
> mwilson@mbp-m2 ~ 127 2$ 
> ```
> 
> It failed the `exec`, but it didn't exit back to the parent, and the redirects aren't in effect.

That is sane behaviour, and it's how I would like ksh to act.

**Comment by McDutchie** [comment]
I'll merge this first, then fix the usability issue separately.

**Comment by McDutchie** [comment]
FYI: https://austingroupbugs.net/view.php?id=1896

**Pull request merged**
