### PR TITLE
Export variables set while `allexport` is on

### PR DESCRIPTION
**Pull request by JohnoKing**
All set variables should be exported while the `allexport` shell option is enabled. This works in most cases, but variables set with `${var:=foo}` aren't successfully exported:
```sh
$ unset foo
$ set -o allexport; test ${foo:=bar}
$ typeset -p foo
foo=bar
$ sh -c 'echo $foo'  # Only prints a newline
```
The bugfix for this problem was backported from ksh2020: https://github.com/att/ast/issues/537

src/cmd/ksh93/sh/name.c:
\- Add a missing instance of `nv_onattr` to set the export flag when `allexport` is enabled.

src/cmd/ksh93/tests/attributes.sh:
\- Backport ksh2020 regression test for the `allexport` option (`set -a`).

### CODE REVIEW

**Comment by McDutchie** [comment]
Hmm. This does not work on mksh or yash, either.

POSIX [specifies](https://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html#tag_18_25_03):
> **-a**
> When this option is on, the export attribute shall be set for each variable to which an assignment is performed; see XBD *[Variable Assignment](https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap04.html#tag_04_23)*.

And a variable assignment there is only defined as the form `varname=value`. Technically, assignments done via variable expansions aren't covered. But I don't think the specification is very clear at all.

There is some [prior discussion](https://www.mail-archive.com/austin-group-l@opengroup.org/msg02754.html) on austin-group-l but it doesn't mention assignments done via variable expansions. I'll have to try to rekindle that discussion in hopes of getting some clarity.

**Comment by McDutchie** [comment]
Interesting response: https://www.mail-archive.com/austin-group-l@opengroup.org/msg09035.html

Looks like we need a fix for assignment via arithmetic expansion as well.

**Comment by JohnoKing** [comment]
I've found an issue with the `allexport` option not currently fixed in this PR. The `set --man` documentation (and not the ksh(1) man page) states that `set -a` will only set the export attribute for variables without a dot in their name:
> -a              Set the export attribute for each variable whose name does not contain a . that you assign a value in the current shell environment.

The actual behavior differs, as namespace variables will have their export attribute set after `set -a`:

```sh
$ ksh -c 'namespace foo { typeset bar; }; set -a; .foo.bar=foo; typeset -p .foo.bar'
typeset -x .foo.bar=foo
```

As for assignment via arithmetic expansion, that could be fixable by setting `NV_EXPORT` in `nv_open`. Experimental patch below:
```diff
diff --git a/src/cmd/ksh93/sh/name.c b/src/cmd/ksh93/sh/name.c
index 57d7b02d..672fc65d 100644
--- a/src/cmd/ksh93/sh/name.c
+++ b/src/cmd/ksh93/sh/name.c
@@ -1430,6 +1430,8 @@ Namval_t *nv_open(const char *name, Dt_t *root, int flags)
 #endif
 	np = nv_create(name, root, flags, &fun);
 	cp = fun.last;
+	if(np && !(flags&NV_NOASSIGN) && sh_isoption(SH_ALLEXPORT))
+		nv_onattr(np,NV_EXPORT);
 #if NVCACHE
 	if(np && nvcache.ok && cp[-1]!=']')
 	{

```

**Comment by McDutchie** [comment]
The `getopts` builtin doesn't export either when assigning a value to the given variable, though it should.

I think `nv_putval()` would be the obvious function to patch. This should remove the need for all other SH_ALLEXPORT handling.

*edit:* The patch is against the dev branch.

```diff
diff --git a/src/cmd/ksh93/bltins/read.c b/src/cmd/ksh93/bltins/read.c
index 0c652ce6..e24e6b72 100644
--- a/src/cmd/ksh93/bltins/read.c
+++ b/src/cmd/ksh93/bltins/read.c
@@ -801,11 +801,6 @@ int sh_readline(char **names, volatile int fd, int flags, ssize_t size, long tim
 		}
 		while(1)
 		{
-			if(sh_isoption(SH_ALLEXPORT)&&!strchr(nv_name(np),'.') && !nv_isattr(np,NV_EXPORT))
-			{
-				nv_onattr(np,NV_EXPORT);
-				sh_envput(sh.env,np);
-			}
 			if(name)
 			{
 				nv_close(np);
diff --git a/src/cmd/ksh93/sh/name.c b/src/cmd/ksh93/sh/name.c
index 57d7b02d..b927b4bf 100644
--- a/src/cmd/ksh93/sh/name.c
+++ b/src/cmd/ksh93/sh/name.c
@@ -289,8 +289,6 @@ void nv_setlist(register struct argnod *arg,register int flags, Namval_t *typ)
 		flags |= NV_NOSCOPE;
 #endif /* SHOPT_NAMESPACE */
 	flags &= ~(NV_TYPE|NV_ARRAY|NV_IARRAY);
-	if(sh_isoption(SH_ALLEXPORT))
-		flags |= NV_EXPORT;
 	if(sh.prefix)
 	{
 		flags &= ~(NV_IDENT|NV_EXPORT);
@@ -1601,6 +1599,11 @@ void nv_putval(register Namval_t *np, const char *string, int flags)
 #if SHOPT_FIXEDARRAY
 	Namarr_t	*ap;
 #endif /* SHOPT_FIXEDARRAY */
+	if(sh_isoption(SH_ALLEXPORT) && !strchr(np->nvname, '.'))
+	{
+		flags |= NV_EXPORT;
+		nv_onattr(np,NV_EXPORT);
+	}
 	/*
 	 * When we are in an invocation-local scope and we are using the
 	 * += operator, clone the variable from the previous scope.
```

**Comment by JohnoKing** [comment]
I've made an improvement to your above patch, although it doesn't seem to work for all namespace variables just yet (this diff is against the pull request):
```diff
diff --git a/src/cmd/ksh93/bltins/read.c b/src/cmd/ksh93/bltins/read.c
index 0c652ce6..e24e6b72 100644
--- a/src/cmd/ksh93/bltins/read.c
+++ b/src/cmd/ksh93/bltins/read.c
@@ -801,11 +801,6 @@ int sh_readline(char **names, volatile int fd, int flags, ssize_t size, long tim
 		}
 		while(1)
 		{
-			if(sh_isoption(SH_ALLEXPORT)&&!strchr(nv_name(np),'.') && !nv_isattr(np,NV_EXPORT))
-			{
-				nv_onattr(np,NV_EXPORT);
-				sh_envput(sh.env,np);
-			}
 			if(name)
 			{
 				nv_close(np);
diff --git a/src/cmd/ksh93/sh/macro.c b/src/cmd/ksh93/sh/macro.c
index e7112541..b1a61e96 100644
--- a/src/cmd/ksh93/sh/macro.c
+++ b/src/cmd/ksh93/sh/macro.c
@@ -2012,8 +2012,6 @@ retry2:
 				if(sh.subshell)
 					np = sh_assignok(np,1);
 				nv_putval(np,argp,0);
-				if(sh_isoption(SH_ALLEXPORT))
-					nv_onattr(np,NV_EXPORT);  /* export variable */
 				v = nv_getval(np);
 				nulflg = 0;
 				stkseek(stkp,offset);
diff --git a/src/cmd/ksh93/sh/name.c b/src/cmd/ksh93/sh/name.c
index 57d7b02d..3d069914 100644
--- a/src/cmd/ksh93/sh/name.c
+++ b/src/cmd/ksh93/sh/name.c
@@ -289,8 +289,6 @@ void nv_setlist(register struct argnod *arg,register int flags, Namval_t *typ)
 		flags |= NV_NOSCOPE;
 #endif /* SHOPT_NAMESPACE */
 	flags &= ~(NV_TYPE|NV_ARRAY|NV_IARRAY);
-	if(sh_isoption(SH_ALLEXPORT))
-		flags |= NV_EXPORT;
 	if(sh.prefix)
 	{
 		flags &= ~(NV_IDENT|NV_EXPORT);
@@ -1621,6 +1619,12 @@ void nv_putval(register Namval_t *np, const char *string, int flags)
 	sh.argaddr = 0;
 	if(sh.subshell && !nv_local && !(flags&NV_RDONLY))
 		np = sh_assignok(np,1);
+	/* Export the variable if 'set -o allexport' is enabled */
+	if(sh_isoption(SH_ALLEXPORT) && !sh.namespace && !strchr(np->nvname, '.'))
+	{
+		flags |= NV_EXPORT;
+		nv_onattr(np,NV_EXPORT);
+	}
 
 	if(np->nvfun && np->nvfun->disc && !(flags&NV_NODISC) && !nv_isref(np))
 	{
diff --git a/src/cmd/ksh93/tests/attributes.sh b/src/cmd/ksh93/tests/attributes.sh
index dfdf7f3c..ced8179c 100755
--- a/src/cmd/ksh93/tests/attributes.sh
+++ b/src/cmd/ksh93/tests/attributes.sh
@@ -706,13 +706,55 @@ do
 done
 
 # ======
-# https://github.com/att/ast/issues/537
-# Export each variable that gets assigned.
-unset bar
+# Variables with a dot in their name shouldn't be exported.
+# https://github.com/ksh93/ksh/pull/431#issuecomment-1016031467
 set -a
+namespace foo_nam {
+	typeset bar
+	typeset foo
+	typeset baz=baz
+	integer three
+}
+test ${.foo_nam.bar:=BAZ}
+exp='.foo_nam.bar=BAZ'
+got=$(typeset -p .foo_nam.bar)
+[[ $exp == $got ]] || err_exit 'Variable ${.foo_nam.bar} should not be exported' \
+	"(expected $(printf %q "$exp"), got $(printf %q "$got"))"
+.foo_nam.foo=FOO
+exp='.foo_nam.foo=FOO'
+got=$(typeset -p .foo_nam.foo)
+[[ $exp == $got ]] || err_exit 'Variable ${.foo_nam.foo} should not be exported' \
+	"(expected $(printf %q "$exp"), got $(printf %q "$got"))"
+exp='.foo_nam.baz=baz'
+got=$(typeset -p .foo_nam.baz)
+[[ $exp == $got ]] || err_exit 'Variable ${.foo_nam.baz} should not be exported' \
+	"(expected $(printf %q "$exp"), got $(printf %q "$got"))"
+((.foo_nam.three=3))
+exp='typeset -l -i .foo_nam.three=3'
+got=$(typeset -p .foo_nam.three)
+[[ $exp == $got ]] || err_exit 'Variable ${.foo_nam.three} should not be exported' \
+	"(expected $(printf %q "$exp"), got $(printf %q "$got"))"
+
+# Export each variable that gets assigned while the allexport
+# shell option is enabled.
+# https://github.com/ksh93/ksh/pull/431
+unset bar
 test ${bar:=baz}
 exp='typeset -x bar=baz'
 got=$(typeset -p bar)
+[[ $exp == $got ]] || err_exit 'Variable ${bar} should be exported' \
+	"(expected $(printf %q "$exp"), got $(printf %q "$got"))"
+# Set variable in arithmetic expressions
+unset bar
+((bar=1))
+exp='typeset -x bar=1'
+got=$(typeset -p bar)
+[[ $exp == $got ]] || err_exit 'Variable ${bar} should be exported' \
+	"(expected $(printf %q "$exp"), got $(printf %q "$got"))"
+unset bar
+test $((bar=2))
+exp='typeset -x bar=2'
+got=$(typeset -p bar)
 [[ $exp == $got ]] || err_exit 'Variable ${bar} should be exported' \
 	"(expected $(printf %q "$exp"), got $(printf %q "$got"))"
 set +a
```
Three of the added regression tests for namespace variables fail:
```
$ bin/shtests -p attributes
#### Regression-testing /home/johno/GitRepos/KornShell/ksh/arch/linux.i386-64/bin/ksh ####
test attributes begins at 2022-01-18+20:17:30
	attributes.sh[721]: FAIL: Variable ${.foo_nam.bar} should not be exported (expected '.foo_nam.bar=BAZ', got 'typeset -x .foo_nam.bar=BAZ')
	attributes.sh[726]: FAIL: Variable ${.foo_nam.foo} should not be exported (expected '.foo_nam.foo=FOO', got 'typeset -x .foo_nam.foo=FOO')
	attributes.sh[735]: FAIL: Variable ${.foo_nam.three} should not be exported (expected 'typeset -l -i .foo_nam.three=3', got 'typeset -x -l -i .foo_nam.three=3')
test attributes failed at 2022-01-18+20:17:30 with exit code 3 [ 156 tests 3 errors ]
Total errors: 3
```

**Comment by McDutchie** [comment]
Actually, I think it is correct that variables declared within namespaces are exported. The following is my current understanding of how it works.

First of all, dot variables are stored in separate trees, one per namespace, e.g. `.foo_nam.bar` is stored in a separate tree for `.foo_nam.*` variables.

While a namespace is active, that tree is temporarily attached to `sh.var_tree` using `dtview`(3) using the shell function scoping mechanism. So during that time, the variables are (also) named `bar`, etc. And during that time, if `bar` has the export attribute, it is actually exported, e.g., it shows up in the output of `env`.

But outside the namespace, those variables are separated from the normal variable namespace as that view is detached, so they are not considered for export by sh_envgen(). Of course they still keep their `-x` typeset attributes but you won't see them when running the `env` command.

So I think that behaviour is actually correct. Names containing dots are never actually exported even if the variables do have the `-x` attributes. They are only exported, sans dots, while their namespace is the active one. We should not do anything special to exclude namespaces from allexport.

**Comment by McDutchie** [comment]
New version pushed. LGTY?

**Comment by JohnoKing** [comment]
The new version works well on my system. I've pushed a few commits that should fix up any remaining issues.

**Comment by McDutchie** [comment]
> Actually, I think it is correct that variables declared within namespaces are exported. The following is my current understanding of how it works.
[…]

Unfortunately it appears that my current understanding is incorrect.

```
$ arch/*/bin/ksh -ac '.ns=; .ns.foo=bar; env|grep foo=bar; typeset -p .ns.foo'
.ns.foo=bar
typeset -x .ns.foo=bar
```
The variable with the dots was actually exported. Yet, when using a `namespace` block, it isn't:
```
$ arch/*/bin/ksh -ac 'namespace ns { foo=bar; }; env|grep foo=bar; typeset -p .ns.foo'
typeset -x .ns.foo=bar
```

Inconsistencies like these are why I want to redesign the namespace mechanism.

In the meantime, back to the drawing board. \<sigh>

**Comment by McDutchie** [comment]
Except, this fix doesn't cause that problem, it was always there:
```
$ ksh-2020.0.1 -ac 'echo ${.sh.version}; .ns=; .ns.foo=bar; env|grep foo=bar; typeset -p .ns.foo'
Version A 2020.0.0-8-ge4fea8c5
.ns.foo=bar
typeset -x .ns.foo=bar
$ /bin/ksh -ac 'echo ${.sh.version}; .ns=; .ns.foo=bar; env|grep foo=bar; typeset -p .ns.foo'
Version AJM 93u+ 2012-08-01
.ns.foo=bar
typeset -x .ns.foo=bar
```

**Comment by hyenias** [comment]
@McDutchie I believe your comment at https://github.com/ksh93/ksh/pull/431#issuecomment-1027567400 is correct. Your assessment of exporting variables seems to be true. Later on, you might have gotten a little mixed up with creating variables with dots in them within the global/default namespace as compared to actually creating namespace variables. Side note: compound variables have dots in them as well; perhaps all the documentation referencing variables with dots in them meant namespace variables.

```
(
set -a
# --- Creating variables with a dots in them. These are not namespace variables.
.dotvar=; .dotvar.foo=bar
echo --- Check to see if variables with dots in them have the -x attribute
typeset -p .dotvar .dotvar.foo
# --- Create namespace ns with variable
namespace ns {
	foo=bar
}
echo --- Check to see if ns namespace variable has the -x attribute
typeset -p .ns
echo --- Check global/default environment view
env|grep foo # Output global/default namespace
echo --- Check namespace ns environment view
namespace ns {
	env|grep foo # output environment from the namespace ns view. should contain global and ns views
}
set +a
)

#### OUTPUT:
--- Check to see if variables with dots in them have the -x attribute
typeset -x .dotvar=''
typeset -x .dotvar.foo=bar
--- Check to see if ns namespace variable has the -x attribute
namespace ns
{
	typeset -x foo=bar
}
--- Check global/default environment view
.dotvar.foo=bar
--- Check namespace ns environment view
.dotvar.foo=bar
foo=bar
```

**Comment by hyenias** [comment]
From my viewpoint, ksh's current behavior of limiting a namespace's exported variables to that namespace's context is preferable as compared to allowing the namespace's exported variables to influence the global/default namespace's view.

**Comment by McDutchie** [comment]
For now I'll just merge this. It certainly improves the situation and, on second thought, doesn't actually appear to introduce new inconsistencies.

**Pull request merged**
