### PR TITLE
Backport `-P` and `-t` flags for `type`/`whence` from ksh93v-

### PR DESCRIPTION
**Pull request by JohnoKing**
This pull request backports the `-P` and `-t` flags for the `whence` and `type` commands from ksh93v-. The `-t` flag is useful when one needs to identify the type of a command. Example:
```sh
$ foo() {; true; }; alias bar=foo
$ type -t foo bar df fg time
function
alias
file
builtin
keyword
```
The `-P` option is simply an alias for the existing `-p` flag:
```sh
$ type -P kill
/bin/kill
$ type -p kill
/bin/kill
```
Both of these were added in ksh93v- for compatibility with Bash.

It should be noted the `-t` option in ksh93v- had one bug, which this pull request fixes. Path-bound builtins from `/opt/ast/bin` were classified as files if loaded from `/opt/ast/bin` in the PATH. Reproducer:
```sh
$ PATH=/opt/ast/bin whence -t cat
file
```

Changes:
\- Simplified the bitmask values for the `command` and `whence` builtin flags.
\- Added the `-t` and `-P` flags to the `whence` and `type` builtins. To prevent bugs `-t` will always override `-v` if both of those flags were passed.
\- Documented the new `-t` and `-P` flags.

Note: Most of the changes in this pull request were taken from my extras branch with `git cherry-pick`, then extended with additional documentation.

### CODE REVIEW

**Comment by McDutchie** [comment]
Whoops, thanks for that typo fix. I've got one more improvement for the documentation and then it's good to go.

**Comment by McDutchie** [comment]
LGTY?

The `-p|P` notation is not used anywhere else that I know of, and I thought it was sort of confusing, so I figured a brief separate line is better. Interesting that optget(3) parses that, though. We could decide to use it, but we should hunt down and change all the option equivalents then for consistency's sake.

**Comment by JohnoKing** [comment]
> The `-p|P` notation is not used anywhere else that I know of, and I thought it was sort of confusing, so I figured a brief separate line is better.

Huh. I could've sworn ksh used that notation quite frequently for its builtins, but a quick grep shows that the builtins documented in `src/cmd/ksh93/data/builtins.c` don't actually use it. Despite that the `/opt/ast/bin` builtins use that notation quite a bit. Some excerpts from libcmd:
https://github.com/ksh93/ksh/blob/d40d998e3a3598c4779076f86790ce571588eccf/src/lib/libcmd/rm.c#L42
https://github.com/ksh93/ksh/blob/d40d998e3a3598c4779076f86790ce571588eccf/src/lib/libcmd/rm.c#L51
https://github.com/ksh93/ksh/blob/d40d998e3a3598c4779076f86790ce571588eccf/src/lib/libcmd/rm.c#L55
https://github.com/ksh93/ksh/blob/d40d998e3a3598c4779076f86790ce571588eccf/src/lib/libcmd/join.c#L63
https://github.com/ksh93/ksh/blob/d40d998e3a3598c4779076f86790ce571588eccf/src/lib/libcmd/cp.c#L54
https://github.com/ksh93/ksh/blob/d40d998e3a3598c4779076f86790ce571588eccf/src/lib/libcmd/cp.c#L62
https://github.com/ksh93/ksh/blob/d40d998e3a3598c4779076f86790ce571588eccf/src/lib/libcmd/cp.c#L64
https://github.com/ksh93/ksh/blob/d40d998e3a3598c4779076f86790ce571588eccf/src/lib/libcmd/cp.c#L97
https://github.com/ksh93/ksh/blob/d40d998e3a3598c4779076f86790ce571588eccf/src/lib/libcmd/cp.c#L101
https://github.com/ksh93/ksh/blob/d40d998e3a3598c4779076f86790ce571588eccf/src/lib/libcmd/cp.c#L122
https://github.com/ksh93/ksh/blob/d40d998e3a3598c4779076f86790ce571588eccf/src/lib/libcmd/chgrp.c#L57
https://github.com/ksh93/ksh/blob/d40d998e3a3598c4779076f86790ce571588eccf/src/lib/libcmd/cat.c#L51

I personally would prefer to use `p|P` for consistency with libcmd.

*EDIT:* I've found that the `test` builtin doesn't use that notation:
https://github.com/ksh93/ksh/blob/d40d998e3a3598c4779076f86790ce571588eccf/src/cmd/ksh93/data/testops.c#L107
https://github.com/ksh93/ksh/blob/d40d998e3a3598c4779076f86790ce571588eccf/src/cmd/ksh93/data/testops.c#L100
https://github.com/ksh93/ksh/blob/d40d998e3a3598c4779076f86790ce571588eccf/src/cmd/ksh93/data/testops.c#L109-L111

**Comment by McDutchie** [comment]
Funny that I hadn't noticed the option alternatives notation using `|` in the /opt/ast/bin built-ins. Very well, we might as well use that everywhere it applies, then.

**Pull request merged**
