### PR TITLE
Fix a compilation error on 32-bit system.

### PR DESCRIPTION
**Pull request by hyousatsu**
related issue:
https://sourceforge.net/p/cdesktopenv/tickets/161/

### CODE REVIEW

**Comment by McDutchie** [comment]
These changes are all unexplained. How do we know they are correct? Just because it makes it build on one system doesn't make the changes correct.

**Comment by McDutchie** [comment]
I just installed a NetBSD 9.3 i386 virtual machine and built the current ksh code on it. It builds just fine.

I will not be applying these changes until both their correctness and the need for them has been demonstrated.

**Comment by JohnoKing** [comment]
The build error this pull request addresses was introduced in 93u+m's upstream codebase by 237b6df1 (aka #601) and in CDE by [cde@8a24d70d](https://sourceforge.net/p/cdesktopenv/code/ci/8a24d70d5e0f2323243602373ab5338ced890d75/). The error occurs because the `#if` directive wasn't changed to check for `_aso_cas64`.
In the upstream 93u+m codebase this bug was fixed a week after #601 was merged, in commit 9c658713. ~This pull request should be closed because the changes are obsolete. In CDE this bug should be fixed properly by either replacing this change with the aso.c fix in 9c658713, or preferably by updating their copy of ksh to 1.0.8.~

*Edit:* Or perhaps this change isn't so bad. It doesn't make much sense why `asocasptr` should use `_aso_cas64` on 32-bit systems rather than `_aso_cas32` or `_aso_casptr`, or even not do anything if `_aso_cas64` isn't defined. This PR works fine with LLVM 15+ in my testing, so that shouldn't be a concern.

**Comment by McDutchie** [comment]
Thanks for looking into it, @JohnoKing. Alright then, let's merge this.

**Comment by hyousatsu** [comment]
> _Edit:_ Or perhaps this change isn't so bad. It doesn't make much sense why `asocasptr` should use `_aso_cas64` on 32-bit systems rather than `_aso_cas32` or `_aso_casptr`, or even not do anything if `_aso_cas64` isn't defined. This PR works fine with LLVM 15+ in my testing, so that shouldn't be a concern.

Yes, that's the point!

**Pull request merged**
