### PR TITLE
IFix ssue#182

### PR DESCRIPTION
**Pull request by phidebian**
INTRO
=====
As stated in the Issue#182 title, printf %T look pretty bad, only trivial cases looks ok.

Note also that handling this date/time thing is pretty complicated, even gnudate(1) (i.e coreutils::parse_time()) don't handle it correctly.

Yet for this fix, I try to get as close as gdate(1) as possible when make sense.

Sometime ksh (libast) printf %T implement things not supported by gdate(1), for instance 'exact' is not implemented by gdate(1). Then the implementation of a feature (like 'exact') can be inconsistent, sometime it is implemented sometimes not. I decided not to fix theses inconsistencies to avoid potential regressions, i.e one could use the faulty path on purpose and would be broken if fixed.

Some example
date    +'%Y-%m-%d %H:%M:%S'  --date="  now +1 month" => 2022-11-24 06:28:12
printf "%(%Y-%m-%d %H:%M:%S)T\n" "      now +1 month" => 2022-11-01 00:00:00
printf "%(%Y-%m-%d %H:%M:%S)T\n" "exact now +1 month" => 2022-11-24 06:28:12
                                  ^^^^^
As we see here, ksh(1) diverge from gdate(1), yet with 'exact' ksh behave
like date(1).

BUT

F='%Y-%m-%d %H:%M:%S'
date +"$F" --date="      2020-2-3 12:34:56 +1 month" => 2020-03-03 11:34:56
printf "%($F)T\n" "      2020-2-3 12:34:56 +1 month" => 2020-03-03 12:34:56
printf "%($F)T\n" "exact 2020-2-3 12:34:56 +1 month" => 2020-03-03 12:34:56
                   ^^^^^
When 'exact' is not present here we should have zero'ed HH:MM:SS, this
is not fixed here on purpose.

TESTING.
=======
While working on bugs exhibited by the test case given by Martijn, I discovered that actually many other cases would exist, I decided first to write some .sh test files so I could spot printf %T regressions.

I implemented printf-{1..6}.sh. When bringing those file on a top of branch sans fixes into src/cmd/ksh93/tests/ and run then we got

$ bin/shtests printf-{1..6}
. . .
Total errors: 405

FIXES: src/lib/libast/tm/tmfix.c::
==================================
The former code was working for a 1 year month roll over, but fail in multi-year month roll over.

date +"$F" --date=now               => 2022-10-24 07:32:58
date +"$F" --date="      -20 month" => 2021-02-24 07:32:58
printf "%($F)T\n" "exact -20 month" => 2021-02-24 07:32:58
                                          ^ 1 year back OK

date +"$F" --date=now                => 2022-10-24 07:34:25
date +"$F" --date="      -24 month"  => 2020-10-24 07:34:25
printf "%($F)T\n" "exact -24 month"  => 2021-04-24 07:34:25
                                           ^ 2 years back FAIL!

With this fix
date +"$F" --date=now                => 2022-10-24 09:40:48
date +"$F" --date="      -24 month"  => 2020-10-24 09:40:48
printf "%($F)T\n" "exact -24 month"  => 2020-10-24 09:40:48

FIX: src/lib/libast/tm/tmxdate.c
================================
All the other %T bug hide in this file.

tmxdate() is a rudimentary parser, that works on a tokeniser. The tokeniser works fine, the parser has problems.

I spotted the bug as a discrepency on variable usage, there are 2 variable named f and n (Glenn style), I would interpret that as a factor and number. In short when parsing -12, we got '-', set f=-1, then '12' set n=12, and later on we got

	m = (f > 0) ? f * n : n;

That is hard to believe. Theorically, as far as signed number goes, f should hold -1, 1 only, with eventually 0 meaning we didn't decided yet, but strangely enough L502 its default value is -1... The number 'n' should hold only >=0 number with eventually <0 meaning no number seen yet. Still strange we can see things like n=-n on some places meaning n could be <0.

All in all it looks like the original code 'was' probaly almost OK, the /* AHA */ enter the dance, and probably strugle to understand what this spaghetti is doing, then all those debug printf left over.

The fix I propose here is based on a simple assumption, restore the f semantic (-1,1) and n semantic (>=0) then fix all deviation from there.

Further complication in this code, when a number 'n' is not yet needed as a number it hold a char during partial scan with lines like n = *++s;
Indeed as always in this kind of double var usage on long function with switch(), goto's, etc... one lost sigh an crash the variable usage.

The tracking of variable is so messy that even gcc has hard time to track the variable 'n' in a register.
On line L157
	register long	n;
is problematic, it confuses the dwarf/debug, make it hard to debug.

removing the register keyword there, don't jeopardise anything, and don't impact perf indeed as the optimiser (-O2) can do its job.

Now the bulk fix starting point is about replacing

	m = (f > 0) ? f * n : n;

with
        m =  f * n;

And then follow f and n so they keep their semantic (factor, number).

With this fix I got no new regressions, and a better printf %T, other bugs may still exist...

### CODE REVIEW

**Comment by phidebian** [comment]
This is attempt#2 for Issue #182, I tried to document in the commit message, and tried to respect the coding style.

Got no regression compiled -O3 on both gcc and clang on ubuntu LTS 22.04 x64.

**Comment by McDutchie** [comment]
None of the 6 regression test scripts work on macOS. They all output this:
```
test printf-1 begins at 2023-04-05+23:44:42
/bin/date: illegal option -- -
usage: date [-jnRu] [-r seconds|file] [-v[+|-]val[ymwdHMS]]
            [-I[date | hours | minutes | seconds]]
            [-f fmt date | [[[mm]dd]HH]MM[[cc]yy][.ss]] [+format]
/usr/local/src/ksh93/ksh/src/cmd/ksh93/tests/printf-1.sh[46]: warning: not found
test printf-1 passed at 2023-04-05+23:44:42 [ 212 tests 0 errors ]
```

So they don't work, but still "pass".

I also don't want 6 new regression test scripts; I'd like them combined into one.

**Comment by McDutchie** [comment]
Oh I see, the tests all require GNU date, but don't include _common so 'warning' doesn't work.

Sorry but the tests need to be portable, we need to be independent from GNU date.

**Comment by McDutchie** [comment]
So, I fixed up the regression tests to make them work for me. And they do all pass.

**Comment by McDutchie** [comment]
Here is my reproducer from #182 with the `exact` keyword added (I didn't know about that!):

```
gnudate=$(command -v gnudate || command -v gdate || command -v date)
get_ago()
{
	ksh=$(printf "%(%Y-%m-%d %H:%M:%S)T\n" "exact $1 $2 ago")
	gnu=$("$gnudate" --date="$1 $2 ago" +"%Y-%m-%d %H:%M:%S")
}
compare_ago()
{
	get_ago "$1" "$2"
	[[ $ksh == $gnu ]] || get_ago "$1" "$2"  # in case we just crossed a second boundary
	[[ $ksh == $gnu ]] || printf -- '[BUG] %3d %7s ago: ksh: %s != gnu: %s\n' "$1" "$2" "$ksh" "$gnu"
}
for u in years months weeks days hours minutes seconds
do
	for ((i=24; i>=-24; i--))
	do
		compare_ago "$i" "$u"
	done
done
```

The results are certainly much better with the PR! But there are a few issues left:

```
[BUG]  24   weeks ago: ksh: 2022-10-21 00:45:34 != gnu: 2022-10-20 00:45:34
[BUG]  23   weeks ago: ksh: 2022-10-28 00:45:34 != gnu: 2022-10-27 00:45:34
[BUG]  22   weeks ago: ksh: 2022-11-04 00:45:34 != gnu: 2022-11-03 00:45:34
[BUG]  21   weeks ago: ksh: 2022-11-11 00:45:34 != gnu: 2022-11-10 00:45:34
[BUG]  20   weeks ago: ksh: 2022-11-18 00:45:34 != gnu: 2022-11-17 00:45:34
[BUG]  19   weeks ago: ksh: 2022-11-25 00:45:34 != gnu: 2022-11-24 00:45:34
[BUG]  18   weeks ago: ksh: 2022-12-02 00:45:34 != gnu: 2022-12-01 00:45:34
[BUG]  17   weeks ago: ksh: 2022-12-09 00:45:34 != gnu: 2022-12-08 00:45:34
[BUG]  16   weeks ago: ksh: 2022-12-16 00:45:34 != gnu: 2022-12-15 00:45:34
[BUG]  15   weeks ago: ksh: 2022-12-23 00:45:34 != gnu: 2022-12-22 00:45:34
[BUG]  14   weeks ago: ksh: 2022-12-30 00:45:34 != gnu: 2022-12-29 00:45:34
[BUG]  13   weeks ago: ksh: 2023-01-06 00:45:34 != gnu: 2023-01-05 00:45:34
[BUG]  12   weeks ago: ksh: 2023-01-13 00:45:34 != gnu: 2023-01-12 00:45:34
[BUG]  11   weeks ago: ksh: 2023-01-20 00:45:34 != gnu: 2023-01-19 00:45:34
[BUG]  10   weeks ago: ksh: 2023-01-27 00:45:34 != gnu: 2023-01-26 00:45:34
[BUG]   9   weeks ago: ksh: 2023-02-03 00:45:34 != gnu: 2023-02-02 00:45:34
[BUG]   8   weeks ago: ksh: 2023-02-10 00:45:34 != gnu: 2023-02-09 00:45:34
[BUG]   7   weeks ago: ksh: 2023-02-17 00:45:34 != gnu: 2023-02-16 00:45:34
[BUG]   6   weeks ago: ksh: 2023-02-24 00:45:34 != gnu: 2023-02-23 00:45:34
[BUG]   5   weeks ago: ksh: 2023-03-03 00:45:34 != gnu: 2023-03-02 00:45:34
[BUG]   4   weeks ago: ksh: 2023-03-10 00:45:34 != gnu: 2023-03-09 00:45:34
[BUG]   3   weeks ago: ksh: 2023-03-17 00:45:34 != gnu: 2023-03-16 00:45:34
[BUG]   2   weeks ago: ksh: 2023-03-24 00:45:34 != gnu: 2023-03-23 00:45:34
[BUG]   1   weeks ago: ksh: 2023-03-31 00:45:34 != gnu: 2023-03-30 00:45:34
[BUG]  24   hours ago: ksh: 2023-04-06 00:45:34 != gnu: 2023-04-05 00:45:34
```

Note that '24 hours ago' seems to be the same as 'now'.

**Comment by McDutchie** [comment]
'24 hours ago' is in fact the same as 'now'. All the 'hours ago' seems to be off by 24 hours:

```
$ TZ=UTC LC_TIME=C arch/darwin.arm64-64/bin/ksh -c 'printf "%T\n" "now" "24 hours ago" "48 hours ago" "72 hours ago"'
Thu Apr  6 00:52:07 UTC 2023
Thu Apr  6 00:52:07 UTC 2023
Wed Apr  5 00:52:07 UTC 2023
Tue Apr  4 00:52:07 UTC 2023
```

**Comment by McDutchie** [comment]
I retested the above issues and I cannot reproduce them now. Odd.

**Comment by McDutchie** [comment]
It seems that, if we just make sure that TZ is exported to whatever valid timezone, then GNU date and ksh agree.

**Comment by McDutchie** [comment]
The regression tests need a lot of work. I don't want five new scripts and I don't want the (re)generation code; I like a more KISS approach. It's also not ideal to require GNU date, but that can't really be avoided. I'm working on it.

**Comment by McDutchie** [comment]
Some of the failures are intermittent. Just now I am getting:
```
$ (export TZ=UTC; printf '%(%Y-%m-%d %H:%M:%S)T\n' 'exact 40 hours ago'; gdate +'%Y-%m-%d %H:%M:%S' -d '40 hours ago')
2023-05-17 00:12:23
2023-05-16 00:12:23
```
…and those should be identical.

**Comment by McDutchie** [comment]
This should be a consistent reproducer:

```
$ TZ=UTC printf '%(%Y-%m-%d %H:%M:%S)T\n' '#1684340457 exact 40 hours ago'                  
2023-05-17 00:20:57
```
Expected output:
```
2023-05-16 00:20:57
```

**Comment by phidebian** [comment]
On Wed, May 17, 2023 at 6:24 PM Martijn Dekker ***@***.***>
wrote:

> This should be a consistent reproducer:
>
> $ TZ=UTC printf '%(%Y-%m-%d %H:%M:%S)T\n' '#1684340457 exact 40 hours ago'
> 2023-05-17 00:20:57
>
> Expected output:
>
> 2023-05-16 00:20:57
>
> Hum, scratching head, I can't really investigate before June 6th at best.
The result you gave are from the latest dev branch f9b081f
<https://github.com/ksh93/ksh/commit/f9b081fae8575e96f45738697e4427c01f4d070a>
I guess I will start from ther.

Cheers
Phi

**Comment by McDutchie** [comment]
No, I am testing this PR, not the dev branch.

The following failures (from the printf.sh regression tests on the current version of this PR) occurred on 17 May 2023 between 17:00 and 17:59 BST (16:00 and 16:59 UTC). At exactly 18:00 BST (17:00 UTC), these tests started passing again.

```
	printf.sh[321]: FAIL: check against GNU 'date': printf '%(%Y-%m-%d %H:%M:%S)T' 'exact -40 hours': expected '2023-05-16 00:56:49', got '2023-05-17 00:56:49'
	printf.sh[504]: FAIL: check against GNU 'date': printf '%(%Y-%m-%d %H:%M:%S)T' 'exact 40 hours ago': expected '2023-05-16 00:56:50', got '2023-05-17 00:56:50'
	printf.sh[518]: FAIL: check against GNU 'date': printf '%(%Y-%m-%d %H:%M:%S)T' 'exact 40 hours ago': expected '2023-05-16 00:56:50', got '2023-05-17 00:56:50'
```

**Comment by McDutchie** [comment]
So, this still fails:

```
$ TZ=UTC printf '%(%Y-%m-%d %H:%M:%S)T\n' '#1684340457 exact 40 hours ago'
2023-05-17 00:20:57
```

(wrong date, should be 2023-05-16)

but this (2518 secs later) passes:

```
$ TZ=UTC printf '%(%Y-%m-%d %H:%M:%S)T\n' '#1684342975 exact 40 hours ago'
2023-05-16 01:02:55
```

**Comment by phidebian** [comment]
Ha ok, will resume from https://github.com/phidebian/ksh/tree/bug-182-2 

Sorry for the confusion

**Comment by phidebian** [comment]
On Wed, May 17, 2023 at 7:05 PM Martijn Dekker ***@***.***>
wrote:

> So, this still fails:
>
> $ TZ=UTC printf '%(%Y-%m-%d %H:%M:%S)T\n' '#1684340457 exact 40 hours ago'
> 2023-05-17 00:20:57
>
> (wrong date, should be 2023-05-16)
>
Good spot, as I said in my early mails I tried not to update obscure code,
tmfix.c sure is one.

With you test case we enter yet another backward rollover bug...

Fix just this one, other may exist...

**Comment by McDutchie** [comment]
Closing this PR because it has been superseded by #641.

**Pull request closed without merging**
