### PR TITLE
emacs.c: Use a "^R: " prompt for Ctrl+R search

### PR DESCRIPTION
**Pull request by pghvlaans**
This is a cosmetic "merge if you like" PR for the reverse search prompt in emacs mode. There probably isn't any reason to go so far as `pdksh` or `zsh` in putting the prompt on a new line, but I think an added colon and space makes it a little more readable.

The `/` prompt for searching in vi mode seems pretty universal across different `*ksh` varieties, so keeping that as-is would be best.

emacs mode: The current prompt for reverse search, "`^R`", can easily be mistaken for a control character. Use "`^R: `" instead for clarity.

### CODE REVIEW

**Comment by JohnoKing** [comment]
This change may be better off implemented as a configurable variable so that the reverse search prompt can be freely changed. Below is a patch that implements a `$PS5` variable for this purpose (although it's incomplete as it doesn't allow escape sequences):
```diff
diff --git a/src/cmd/ksh93/Mamfile b/src/cmd/ksh93/Mamfile
index fc173dfda..62bd9a97e 100644
--- a/src/cmd/ksh93/Mamfile
+++ b/src/cmd/ksh93/Mamfile
@@ -1284,6 +1284,7 @@ make install
 					prev include/history.h implicit
 					prev include/io.h implicit
 					prev include/defs.h implicit
+					prev include/variables.h implicit
 					prev FEATURE/cmds implicit
 					prev ${PACKAGE_ast_INCLUDE}/releaseflags.h implicit
 					prev ${PACKAGE_ast_INCLUDE}/ast.h implicit
diff --git a/src/cmd/ksh93/data/variables.c b/src/cmd/ksh93/data/variables.c
index b9dfb6136..9091a8237 100644
--- a/src/cmd/ksh93/data/variables.c
+++ b/src/cmd/ksh93/data/variables.c
@@ -101,6 +101,7 @@ const struct shtable2 shtab_variables[] =
 	".sh.ppid",	NV_PID|NV_NOFREE,		(char*)0,
 	".sh.tilde",	0,				(char*)0,
 	"SHLVL",	NV_INTEGER|NV_NOFREE|NV_EXPORT,	(char*)0,
+	"PS5",		NV_NOFREE,			"^R: ",
 	"",	0,					(char*)0
 };
 
diff --git a/src/cmd/ksh93/edit/emacs.c b/src/cmd/ksh93/edit/emacs.c
index a780dd2e7..784b180e3 100644
--- a/src/cmd/ksh93/edit/emacs.c
+++ b/src/cmd/ksh93/edit/emacs.c
@@ -71,6 +71,7 @@ One line screen editor for any program
 #include	"history.h"
 #include	"edit.h"
 #include	"terminal.h"
+#include	"variables.h"
 
 #define ESH_NFIRST
 #define ESH_KAPPEND
@@ -1305,23 +1306,39 @@ static void search(Emacs_t* ep,genchar *out,int direction)
 #ifndef ESH_NFIRST
 	Histloc_t location;
 #endif
-	register int i,sl;
+	int i, savestacktop, sav_cur;
+	size_t sl, maxlen;
+	genchar *string;
 	genchar str_buff[LBUF];
-	register genchar *string = drawbuff;
+	char *savestackptr, *str;
 	/* save current line */
-	int sav_cur = cur;
+	string = drawbuff;
+	sav_cur = cur;
 	genncpy(str_buff,string,sizeof(str_buff)/sizeof(*str_buff));
-	string[0] = '^';
-	string[1] = 'R';
-	string[2] = '\0';
-	sl = 2;
+	/* PS5 prompt. Save stack state to avoid corrupting command substitutions
+	 * in case we're executing a PS5.get discipline function at parse time. */
+	savestacktop = staktell();
+	savestackptr = stakfreeze(0);
+	str = nv_getval(sh_scoped(PS5NOD));
+	if(!str)
+		str = Empty;
+	stakset(savestackptr, savestacktop);
+	maxlen = strlen(str);
+	sl = 0;
+	while(str[sl])
+	{
+		string[sl] = str[sl];
+		++sl;
+	}
+	string[maxlen] = '\0';
+	sl = maxlen;
 	cur = sl;
 	draw(ep,UPDATE);
 	while ((i = ed_getchar(ep->ed,1))&&(i != '\r')&&(i != '\n'))
 	{
 		if (i==usrerase || i==DELETE || i=='\b' || i==ERASECHAR)
 		{
-			if (sl > 2)
+			if (sl > maxlen)
 			{
 				string[--sl] = '\0';
 				cur = sl;
@@ -1368,7 +1385,7 @@ static void search(Emacs_t* ep,genchar *out,int direction)
 	}
 	skip:
 	i = genlen(string);
-	if(ep->prevdirection == -2 && i!=2 || direction!=1)
+	if(ep->prevdirection == -2 && i!=maxlen || direction!=1)
 		ep->prevdirection = -1;
 	if (direction < 1)
 	{
@@ -1377,12 +1394,12 @@ static void search(Emacs_t* ep,genchar *out,int direction)
 	}
 	else
 		direction = -1;
-	if (i != 2)
+	if (i != maxlen)
 	{
 #if SHOPT_MULTIBYTE
 		ed_external(string,(char*)string);
 #endif /* SHOPT_MULTIBYTE */
-		strncopy(lstring,((char*)string)+2,SEARCHSIZE-1);
+		strncopy(lstring,((char*)string)+maxlen,SEARCHSIZE-1);
 		lstring[SEARCHSIZE-1] = 0;
 		ep->prevdirection = direction;
 	}
diff --git a/src/cmd/ksh93/include/variables.h b/src/cmd/ksh93/include/variables.h
index 821d86011..65f83172b 100644
--- a/src/cmd/ksh93/include/variables.h
+++ b/src/cmd/ksh93/include/variables.h
@@ -111,5 +111,6 @@ extern void sh_save_rand_seed(struct rand *, int);
 #define SH_PPIDNOD	(sh.bltin_nodes+63)
 #define SH_TILDENOD	(sh.bltin_nodes+64)
 #define SHLVL		(sh.bltin_nodes+65)
+#define PS5NOD		(sh.bltin_nodes+66)
 
 #endif /* SH_VALNOD */
```

**Comment by pghvlaans** [comment]
Do any other shells go up as high as `$PS5`?

**Comment by JohnoKing** [comment]
> Do any other shells go up as high as `$PS5`?

None that I'm aware of.

**Comment by McDutchie** [comment]
All the other PS? prompts are not editor-specific and even apply when neither line editor is enabled. I am not fond of the idea of an editor-specific PS5 variable. If we want such a variable it should be called something else. I tend to think this borders on featuritis though.

**Comment by pghvlaans** [comment]
Thank you for the merge. It's still working as expected.

**Comment by McDutchie** [comment]
This little change is nice to have, so I'll just merge this PR now. I think it can even be backported for 1.0.4 as the change is cosmetic only, and should not affect any scripts.

I'm open to being convinced about the desirability of making this prompt customisable. If that is really wanted, it can be dealt with in a new PR.

**Pull request merged**
