### PR TITLE
Fix various minor problems and update the documentation

### PR DESCRIPTION
**Pull request by JohnoKing**
These are minor fixes I've accumulated over time. The following changes are somewhat notable:
\- Added a missing entry for `typeset -s` to the man page.
\- Removed the man page the entry for ksh reading `$PWD/.profile` on login. That feature was removed in commit aa7713c2.
\- Added `date(1)` and `strftime(3)` to the 'see also' section of the man page.
\- Note that the `hash` command can be used instead of `alias -t` to workaround one of the caveats listed in the man page.
\- Use an 'out of memory' error message rather than 'out of space' when memory allocation fails (this change is to avoid grouping out of memory errors with disk space errors).
\- Replaced backticks with quotes in some places for consistency.
\- Added missing documentation for the `%P` date format.
\- Added missing documentation for `printf %Q` and `printf %p` (backported from ksh2020: https://github.com/att/ast/pull/1032).
\- The comments that show each builtin's options have been updated.

### CODE REVIEW

**Comment by hyenias** [comment]
Just a little check yourself question: When you swapped out all the "out of space" messages to "out of memory" could there have been any instances where the "out of space" message referred to failed disk/file usage attempts? Perhaps, unable to open a file, close a file, find a file, or etc. rather than unable to allocate memory.

**Comment by JohnoKing** [comment]
I avoided changing the error messages to "out of memory" unless the error was because of a failed memory allocation (the error messages are placed after calls like `newof`, `getcwd` and `vmstrdup`). In the case of `REG_ESPACE` it's always used after a memory allocation error, although the current pull request keeps the old name. It's not used much outside of the regex code, so I'll change that to `REG_ENOMEM` in the next commit.

**Comment by McDutchie** [comment]
Please don't change the public libast API, i.e.: the name of any identifier in a header that might be included by another program. There has been some interest in possibly maintaining libast as a separate project (ping @lkujaw) and in any case we might want to compile something else against it someday.

That type of change also makes it more difficult to backport fixes (either for us, or for others who want to take some of our fixes).

If you think it's needed for clarity, you can add a brief comment to the usage of identifiers like GLOB_NOSPACE that actually refer to an out of memory condition.

**Comment by McDutchie** [comment]
LGTM now, thanks for all this work.

**Pull request merged**
