### PR TITLE
Fix printf %(dateformat)T with relative date spec (#182)

### PR DESCRIPTION
**Pull request by phidebian**
On backward rollover tmfix.c was missing more case.
    
            if ((n = tm->tm_hour) < 0)
            {
                    tm->tm_mday -= (23 - n) / 24;
                    tm->tm_hour = 24 - (-n) % 24;
                    if(tm->tm_hour>=24)
                    {
                      tm->tm_hour = 0;
                    }
            }
    We can enter this witn n=-24, then tm->tm_hour = 24 - (-n) % 24 is a NOP
    which is not good.

### CODE REVIEW

**Comment by McDutchie** [comment]
Prior discussion and fix description at: #569

Opening new PRs is not necessary and only crowds the list of PRs, fragments the discussion threads, and generally makes things more complicated. I would appreciate it if, in future, you could simply add new commits to the existing PR/branch.

**Comment by McDutchie** [comment]
Having said that though, I'm impressed with the fix (I never was able to wrap my head around this) and I'm very happy 1.0.5 will have these egregious bugs fixed. Thank you very much. I'm working on merging this now.

**Comment by phidebian** [comment]
On Thu, May 18, 2023 at 7:46 PM Martijn Dekker ***@***.***>
wrote:

> I very much appreciate and welcome your work, but I wish you'd stop
> opening new PRs. It is unnecessary and only crowds the list of PRs and
> makes things more complicated. In future, please simply add new commits to
> the existing PR/branch.
>

Ha, got it, I was disorientated myself by all this issue# discussion# and
got very hard time to follow, and retrieve, informations I wrote. I think I
really miss a single mailing list (like bash-bug) where all the discution
thread would go, and you could use your mailer to retrieve things.

I am not that fluent in git/github, and when I learned how to make a PR,
like a wild hog that always retake the same path, I was doing PR again and
again. Next round I will try push new commit on my PR branchj and see what
hap.

Cheers

**Comment by McDutchie** [comment]
Thanks, much appreciated!

**Pull request merged**
