### PR TITLE
Add support for more keyboard shortcuts

### PR DESCRIPTION
**Pull request by JohnoKing**
This pull request implements more keyboard shortcuts for use with the emacs and vi editing modes. List of changes:

- Added support for Home key sequences `^[[1~` and `^[[7~` as well as End key sequences `^[[4~` and `^[[8~`.

- Added support for the following keyboard shortcuts:
  - Ctrl-Left Arrow:  Go back one word
  - Alt-Left Arrow:   Go back one word
  - Ctrl-Right Arrow: Go forward one word
  - Alt-Right Arrow:  Go forward one word
  - Ctrl-G:           Cancel reverse search
  - Ctrl-Delete:      Delete next word

- Added a keybind for the Insert key, which differs in the emacs and vi editing modes:
  - In emacs mode, Insert escapes the next character.
  - In vi mode, Insert will switch the editor to insert mode (like in vim).

### CODE REVIEW

**Comment by McDutchie** [comment]
Are these escape sequences platform-specific? I'm afraid none of this is working on my end (macOS 10.14.6). In one aspect, the behaviour differs depending on whether I use the default Terminal.app or [iTerm2](https://iterm2.com).

### emacs: ###

On Terminal.app, the patch seems to cause no change at all. Both before and after the patch:
* Ctrl+left/right arrow is ignored
* Alt+left/right arrow causes the cursor to jump to the previous/next word
* Command+left/right arrow is ignored
* Insert is ignored

iTerm, before the patch:
* Ctrl+left/right arrow is ignored
* Alt+left arrow enters `;9D`; Alt+right arrow enters `;9C`
* Command+left/right arrow switches between tabs
* Insert is ignored

iTerm, after the patch:
* Ctrl+left/right arrow is ignored
* Alt+left arrow enters `1D`; Alt+right arrow enters `1C`
* Command+left/right arrow switches between tabs
* Insert is ignored

### vi (insert mode): ###

Terminal.app, both before and after the patch:
* Ctrl+left/right arrow is ignored
* Alt-left arrow beeps, then moves to the previous word; Alt-right arrow beeps and does nothing on the first press and does nothing at all on subsequent presses
* Command+left/right arrow is ignored
* Insert is ignored

iTerm, both before and after the patch:
* Ctrl+left/right arrow is ignored
* Alt-left arrow beeps, then deletes to the end of line placing the cursor over the current/last character; Alt-right arrow beeps, then deletes to the end of line placing the cursor to the right of the current/last character
* Command+left/right arrow switches between tabs
* Insert is ignored

**Comment by JohnoKing** [comment]
These unfortunately are rather platform specific, as I've found terminal emulators differ from each other as to how keys are registered. The patch in it's current form was tested on Linux, FreeBSD and illumos (using vt, xterm, xfce4-terminal, gnome-terminal, kitty and konsole). On all of those terminals the patch should work, although I've found that on a plain Linux tty Ctrl+Left/Right Arrow don't work (which I'll note doesn't work in Bash either, as on a plain Linux tty Ctrl doesn't change the control sequences for the arrow keys). **Edit:** I've pushed some additional changes that should allow much of this patch to work on Haiku's terminal as well.

I probably could add support for the Terminal.app and iTerm2 sequences, but I don't have a Mac to test it on and I can't find any information as to what the control sequences are for those terminals. I would appreciate it if you could post what those are; to get them use Ctrl+V followed by the keyboard shortcut (it'd also be nice to know if the keyboard shortcuts work when using Bash with Terminal.app and iTerm2). Below is a list of key sequences this patch currently adds support for, so if you get different results from Ctrl+V then it's because I didn't implement it in the patch:

| Shortcut               | Sequence  |
|-------------------|------------|
| Ctrl+Left Arrow    | `^[[1;5D`   |
| Alt+Left Arrow      | `^[[1;3D`   |
| Ctrl+Right Arrow  | `^[[1;5C`  |
| Alt+Right Arrow   | `^[[1;3C` |
| Ctrl+Delete          | `^[[3;5~` |
| Insert                    | `^[[2~` |
| Home                   | `^[[1~` |
| Home                   | `^[[7~` |
| End                      | `^[[4~` |
| End                      | `^[[8~` |
| Ctrl+G (reverse search only) | `^G` |

| Haiku terminal bindings: |      |
|-------------------|------------|
| Up Arrow            | `^[OA` |
| Down Arrow            | `^[OB` |
| Right Arrow            | `^[OC` |
| Ctrl+Right Arrow  | `^[O5C`  |
| Left Arrow            | `^[OD` |
| Ctrl+Left Arrow    | `^[O5D`   |

Additionally, the patch below might fix Alt+Left/Right Arrow in iTerm, though it's more of a guess than anything:
```diff
diff --git a/src/cmd/ksh93/edit/emacs.c b/src/cmd/ksh93/edit/emacs.c
index 405b6dbe..7d1a8811 100644
--- a/src/cmd/ksh93/edit/emacs.c
+++ b/src/cmd/ksh93/edit/emacs.c
@@ -1149,7 +1149,7 @@ static int escape(register Emacs_t* ep,register genchar *out,int count)
 				else if(i == '1' && ch == ';')
 				{
 					ch = ed_getchar(ep->ed,1);
-					if(ch == '3' || ch == '5') /* 3 == Alt, 5 == Ctrl */
+					if(ch == '3' || ch == '5' || ch == '9') /* 3 == Alt, 5 == Ctrl, 9 == iTerm Alt */
 					{
 						switch(ed_getchar(ep->ed,1))
 						{
diff --git a/src/cmd/ksh93/edit/vi.c b/src/cmd/ksh93/edit/vi.c
index 02289a89..fbcda8df 100644
--- a/src/cmd/ksh93/edit/vi.c
+++ b/src/cmd/ksh93/edit/vi.c
@@ -1677,7 +1677,7 @@ static int mvcursor(register Vi_t* vp,register int motion)
 			else if(motion=='1' && bound==';')
 			{
 				bound = ed_getchar(vp->ed,-1);
-				if(bound == '3' || bound == '5') /* 3 == Alt, 5 == Ctrl */
+				if(bound == '3' || bound == '5' || bound == '9') /* 3 == Alt, 5 == Ctrl, 9 == iTerm Alt */
 				{
 					switch(ed_getchar(vp->ed,-1))
 					{
```

**Comment by posguy99** [comment]
I use this as a reference.

https://github.com/timothybasanov/terminal-app-function-keys

**Comment by hyenias** [comment]
I did not realize that terminal sequences were being hard coded into the ksh code base. I would think that ksh should query the terminal database (terminfo/tput/ncurses api/etc.) to retrieve the correct terminal sequencing for a particular action. I realize that perhaps that was not necessary for the basics as they are mostly standardize but it does appear that the more advance actions or keystrokes require a greater level of flexibility which the local terminal database provides.

I believe I recall some ksh code here-and-here that uses the `tput` command to retrieve the control sequences. Not sure if one query with terminfo or tput could be done to gather all the needed inputs. If launching multiple OS calls to retrieve the terminal info is too impactful to the startup of an interactive session, then perhaps only call/make the OS call to retrieve the control sequence(s) when first used then store that result for later use. Perhaps, multiple results could be obtained for a category of interactive screen actions such as fetching all the CTRL + \<arrow key\> sequences on the first use; the same would follow with ATL + \<arrow keys\>, so and so forth...

**Comment by hyenias** [comment]
Here is an example for using tput to return more than one terminal database entry from the terminfo database. See infocmp for terminfo descriptions.
```ksh
{
# cr\n is used as a deliminator between the tput parameters
unset s t_ccu1 t_clear
s=${ tput -S <<< $'cr\ncuu1\ncr\nclear\n'; }
IFS=${s%%$'\E'*} read -r t_ccu1 t_clear <<< "$s"
typeset -p s t_ccu1 t_clear
}
# output using Alacritty on macOS
s=$'\r\E[A\r\E[H\E[2J\E[3J'
t_ccu1=$'\E[A'
t_clear=$'\E[H\E[2J\E[3J'
```

**Comment by JohnoKing** [comment]
Querying the terminfo database would be more foolproof than hardcoding escape sequences, but it would likely require a major rewrite to pull off (which is out of the scope of what I intended to do with this patch).

**Comment by McDutchie** [comment]
> I probably could add support for the Terminal.app and iTerm2 sequences, but I don't have a Mac to test it on and I can't find any information as to what the control sequences are for those terminals. I would appreciate it if you could post what those are;

| Shortcut               | Terminal.app  | iTerm2  | Works on bash<br/>(Terminal.app) | Works on bash<br/>(iTerm2) |
|-------------------|--------------|---------|----------------|------------|
| Ctrl+Left Arrow    | (ignored)   |    (ignored) |  no | no |
| Alt+Left Arrow      |  `^[b` | `^[[1;9D` | yes | no |
| Ctrl+Right Arrow  | (ignored)   |    (ignored) |  no | no |
| Alt+Right Arrow   | `^[f` | `^[[1;9C` | yes | no |
| Ctrl+Delete          | (beeps) | `^[[3;5~` | no | yes |
| Insert                    | (ignored)   |    (ignored) |  no | no |
| Home                   | `^[[H` | `^[[H` | yes | yes |
| End                      | `^[[F` | `^[[F` | yes | yes |

> Additionally, the patch below might fix Alt+Left/Right Arrow in iTerm, though it's more of a guess than anything:

That works fine, actually.

**Comment by McDutchie** [comment]
I don't think this code is quite right yet because it eats unhandled keystrokes, i.e., it does not put all unhandled input back into the edit buffer using `ed_ungetchar()`. I'm pushing a commit that I believe fixes this for emacs, but I don't have time to properly test it right now. Could you test it? If that looks good I'll do the same for vi, or you can do if you want to.

**Comment by JohnoKing** [comment]
That change should be fine. I've pushed a new commit that avoids eating unhandled key strokes in vi mode and improves the emacs mode handling as well.

**Pull request merged**
