### PR TITLE
Fix `read -a` failure to create array (re: 4d182da8)

### PR DESCRIPTION
**Pull request by JohnoKing**
The commit that backported `read -a` did not add a case label for it to read.c. This was under the assumption that `optget` would always convert `-a` to `-A`, although this doesn't seem to be very consistent behavior. After running `read -a` or `read -A` once, the `-a` flag will fail to to create an array (`-A` is unaffected). Reproducer:
```sh
$ read -A foo <<< 'foo bar baz'
$ unset foo
$ read -a foo <<< 'foo bar baz'
$ echo ${foo[0]}
foo bar baz
$ echo ${foo[1]}

$ read -A foo <<< 'foo bar baz'
$ echo ${foo[0]}
foo
$ echo ${foo[1]}
bar
```

src/cmd/ksh93/bltins/read.c:
\- Add case label for the `read` builtin's `-a` flag.

src/cmd/ksh93/tests/builtins.sh:
\- Add regression tests for this bug. For consistency these are all run in a separate script.

### CODE REVIEW

**Comment by McDutchie** [comment]
This looks like a bug in optget(3). It would be better to fix that instead, if possible.

**Comment by McDutchie** [comment]
Disabling the options cache for option equivalents after '|' seems to make the problem go away. I don't know if that's the best or most correct fix but it seems to work.
```diff
diff --git a/src/lib/libast/misc/optget.c b/src/lib/libast/misc/optget.c
index d8ed23a0a..2ae3b5801 100644
--- a/src/lib/libast/misc/optget.c
+++ b/src/lib/libast/misc/optget.c
@@ -4992,7 +4992,6 @@ optget(register char** argv, const char* oopts)
 								f += 2;
 								if (!(j = *f) || j == '!' || j == '=' || j == ':' || j == '?' || j == ']')
 									break;
-								cache->flags[map[j]] = m;
 							}
 							if (j != '!' || (m & OPT_cache_invert))
 								break;
```

**Comment by McDutchie** [comment]
Other commands may have this problem, e.g. the /opt/ast/bin/cp built-in: https://github.com/ksh93/ksh/blob/daf4e0b0cf81876c4785c898accc11665b5c3d39/src/lib/libcmd/cp.c#L60-L61 https://github.com/ksh93/ksh/blob/daf4e0b0cf81876c4785c898accc11665b5c3d39/src/lib/libcmd/cp.c#L845-L849 There is no `case 'd':` label.

**Comment by JohnoKing** [comment]
The optget patch doesn't fix this problem completely. In the case of the `rm` builtin, removing the case label for `-r` causes it to break (despite being the same as `-R`).
<details open>
<summary>Test patch</summary>

```diff
diff --git a/src/cmd/ksh93/data/builtins.c b/src/cmd/ksh93/data/builtins.c
index d31ebe9fb..4a59ba82a 100644
--- a/src/cmd/ksh93/data/builtins.c
+++ b/src/cmd/ksh93/data/builtins.c
@@ -145,6 +145,7 @@ const struct shtable3 shtab_builtins[] =
 	CMDLIST(ln)
 	CMDLIST(mktemp)
 	CMDLIST(mv)
+	CMDLIST(rm)
 #if !_std_malloc && !_AST_std_malloc
 	CMDLIST(vmstate)  /* vmstate only works with vmalloc */
 #endif
diff --git a/src/lib/libast/misc/optget.c b/src/lib/libast/misc/optget.c
index d8ed23a0a..2ae3b5801 100644
--- a/src/lib/libast/misc/optget.c
+++ b/src/lib/libast/misc/optget.c
@@ -4992,7 +4992,6 @@ optget(register char** argv, const char* oopts)
 								f += 2;
 								if (!(j = *f) || j == '!' || j == '=' || j == ':' || j == '?' || j == ']')
 									break;
-								cache->flags[map[j]] = m;
 							}
 							if (j != '!' || (m & OPT_cache_invert))
 								break;
diff --git a/src/lib/libcmd/rm.c b/src/lib/libcmd/rm.c
index dc26bcb38..6a1d04892 100644
--- a/src/lib/libcmd/rm.c
+++ b/src/lib/libcmd/rm.c
@@ -346,7 +346,6 @@ b_rm(int argc, register char** argv, Shbltin_t* context)
 			state.interactive = 1;
 			state.force = 0;
 			continue;
-		case 'r':
 		case 'R':
 			state.recursive = 1;
 			continue;
```

See also:
https://github.com/ksh93/ksh/blob/daf4e0b0cf81876c4785c898accc11665b5c3d39/src/lib/libcmd/rm.c#L51

</details>

Result from applying the patch:
```
$ bin/shtests -p builtins         
#### Regression-testing /home/johno/GitRepos/KornShell/ksh/arch/linux.i386-64/bin/ksh ####
test builtins begins at 2022-08-17+05:55:35
	builtins.sh[1474]: FAIL: rm builtin fails to remove non-empty directory and subdirectory with -rd options (got $'rm: -rd: not found\nrm: /tmp/ksh93.shtests.59060.15567/builtins.C/nonemptydir1: directory')
	builtins.sh[1476]: FAIL: rm builtin fails to remove all folders with -rd options
	builtins.sh[1478]: FAIL: rm builtin fails to remove non-empty directory and file with -rd options (got $'rm: -rd: not found\nrm: /tmp/ksh93.shtests.59060.15567/builtins.C/nonemptydir2: directory')
	builtins.sh[1480]: FAIL: rm builtin fails to remove all folders and files with -rd options
test builtins failed at 2022-08-17+05:55:43 with exit code 4 [ 286 tests 4 errors ]
Total errors: 4
CPU time       user:      system:
main:      0m00.000s    0m00.012s
tests:     0m00.302s    0m00.111s
```

**Comment by McDutchie** [comment]
I think the following patch fixes it correctly; please try. It implements caching for short-option equivalents, which turned out to be fairly simple. In my testing, all the regression tests pass, including those for the `rm` builtin (when enabled) as well as your tests for `read -a`.
<details>
<summary>Patch version 2</summary>

```diff
diff --git a/src/lib/libast/misc/optlib.h b/src/lib/libast/misc/optlib.h
index 3ec626591..a5f1dfd7d 100644
--- a/src/lib/libast/misc/optlib.h
+++ b/src/lib/libast/misc/optlib.h
@@ -71,6 +71,7 @@ typedef struct Optcache_s
 	Optpass_t		pass;
 	int			caching;
 	unsigned char		flags[sizeof(OPT_FLAGS)];
+	char			equiv[sizeof(OPT_FLAGS)];	/* short option equivalents */
 } Optcache_t;

 typedef struct Optstate_s
diff --git a/src/lib/libast/misc/optget.c b/src/lib/libast/misc/optget.c
index d8ed23a0a..a77f1948b 100644
--- a/src/lib/libast/misc/optget.c
+++ b/src/lib/libast/misc/optget.c
@@ -4549,6 +4549,8 @@ optget(register char** argv, const char* oopts)
 		{
 			if (cache)
 			{
+				if (c >= 0 && c < sizeof(map) && map[c] && cache->equiv[map[c]])
+					c = cache->equiv[map[c]];
 				if (k = cache->flags[map[c]])
 				{
 					opt_info.arg = 0;
@@ -4979,6 +4981,7 @@ optget(register char** argv, const char* oopts)
 						v = f;
 						for (;;)
 						{
+							char	eqv;
 							if (isdigit(*f) && isdigit(*(f + 1)))
 								while (isdigit(*(f + 1)))
 									f++;
@@ -4987,12 +4990,17 @@ optget(register char** argv, const char* oopts)
 							else
 								cache->flags[map[*f]] = m;
 							j = 0;
+							/*
+							 * parse and cache short option equivalents,
+							 * e.g. x|y|z means -y and -z yield -x
+							 */
+							eqv = *f;
 							while (*(f + 1) == '|')
 							{
 								f += 2;
 								if (!(j = *f) || j == '!' || j == '=' || j == ':' || j == '?' || j == ']')
 									break;
-								cache->flags[map[j]] = m;
+								cache->equiv[map[j]] = eqv;
 							}
 							if (j != '!' || (m & OPT_cache_invert))
 								break;
diff --git a/src/cmd/ksh93/bltins/whence.c b/src/cmd/ksh93/bltins/whence.c
index 0c783127e..08ccd3613 100644
--- a/src/cmd/ksh93/bltins/whence.c
+++ b/src/cmd/ksh93/bltins/whence.c
@@ -124,7 +124,6 @@ int	b_whence(int argc,char *argv[],Shbltin_t *context)
 	    case 'f':
 		flags |= F_FLAG;
 		break;
-	    case 'P':
 	    case 'p':
 		flags |= P_FLAG;
 		break;
```
</details>

**Comment by JohnoKing** [comment]
The patch doesn't fix the bug. The only reason the regression tests pass with that patch is because it doesn't remove the extra case label for `rm -r`. Removing that still results in regression test failures.
```
$ bin/shtests -p builtins
#### Regression-testing /home/johno/GitRepos/KornShell/ksh/arch/linux.i386-64/bin/ksh ####
test builtins begins at 2022-08-17+06:56:27
	builtins.sh[1474]: FAIL: rm builtin fails to remove non-empty directory and subdirectory with -rd options (got $'rm: -rd: not found\nrm: /tmp/ksh93.shtests.91661.31359/builtins.C/nonemptydir1: directory')
	builtins.sh[1476]: FAIL: rm builtin fails to remove all folders with -rd options
	builtins.sh[1478]: FAIL: rm builtin fails to remove non-empty directory and file with -rd options (got $'rm: -rd: not found\nrm: /tmp/ksh93.shtests.91661.31359/builtins.C/nonemptydir2: directory')
	builtins.sh[1480]: FAIL: rm builtin fails to remove all folders and files with -rd options
test builtins failed at 2022-08-17+06:56:34 with exit code 4 [ 286 tests 4 errors ]
Total errors: 4
```

This is the patch for `rm` I applied on top of [your patch](https://github.com/ksh93/ksh/pull/516#issuecomment-1218021784):
```diff
diff --git a/src/cmd/ksh93/data/builtins.c b/src/cmd/ksh93/data/builtins.c
index d31ebe9fb..4a59ba82a 100644
--- a/src/cmd/ksh93/data/builtins.c
+++ b/src/cmd/ksh93/data/builtins.c
@@ -145,6 +145,7 @@ const struct shtable3 shtab_builtins[] =
 	CMDLIST(ln)
 	CMDLIST(mktemp)
 	CMDLIST(mv)
+	CMDLIST(rm)
 #if !_std_malloc && !_AST_std_malloc
 	CMDLIST(vmstate)  /* vmstate only works with vmalloc */
 #endif
diff --git a/src/lib/libcmd/rm.c b/src/lib/libcmd/rm.c
index dc26bcb38..6a1d04892 100644
--- a/src/lib/libcmd/rm.c
+++ b/src/lib/libcmd/rm.c
@@ -346,7 +346,6 @@ b_rm(int argc, register char** argv, Shbltin_t* context)
 			state.interactive = 1;
 			state.force = 0;
 			continue;
-		case 'r':
 		case 'R':
 			state.recursive = 1;
 			continue;
```

**Comment by JohnoKing** [comment]
Also, I'll note that for some reason the code for `cp -r` and `cp -R` differ, even though the man page for `cp` states these options are the same:
https://github.com/ksh93/ksh/blob/4a351d3fcecb19f3c983e0957228dbeed84cd9af/src/lib/libcmd/cp.c#L92
https://github.com/ksh93/ksh/blob/4a351d3fcecb19f3c983e0957228dbeed84cd9af/src/lib/libcmd/cp.c#L807-L811
https://github.com/ksh93/ksh/blob/4a351d3fcecb19f3c983e0957228dbeed84cd9af/src/lib/libcmd/cp.c#L850-L855

**Comment by McDutchie** [comment]
> The patch doesn't fix the bug. The only reason the regression tests pass with that patch is because it doesn't remove the extra case label for `rm -r`.

You're right that I didn't test that. However: https://github.com/ksh93/ksh/blob/4a351d3fcecb19f3c983e0957228dbeed84cd9af/src/lib/libcmd/rm.c#L51 `r` is the main option letter, `R` is the equivalent. So it is the `'R'` case label you should be removing, not `'r'`. After doing that, the tests pass on my end.

**Comment by McDutchie** [comment]
> Also, I'll note that for some reason the code for `cp -r` and `cp -R` differ, even though the man page for `cp` states these options are the same:

Wow. That is certainly incorrect. With the original optget(3), on the first invocation (before caching), `-R` would have triggered the `'r'` case label and on subequent invocations, the `'R'` one. So we need to figure out which of these implementations is the best one and remove the other, or combine them somehow.

**Comment by JohnoKing** [comment]
Here's an experimental patch that attempts to correct the situation with `cp -r`/`cp -R`. It'll likely need more thorough testing because `ln` and `mv` share code with `cp`. I haven't done proper testing with `-H` yet:
```diff
diff --git a/src/cmd/ksh93/data/builtins.c b/src/cmd/ksh93/data/builtins.c
index d31ebe9fb..9111b97a4 100644
--- a/src/cmd/ksh93/data/builtins.c
+++ b/src/cmd/ksh93/data/builtins.c
@@ -145,6 +145,7 @@ const struct shtable3 shtab_builtins[] =
 	CMDLIST(ln)
 	CMDLIST(mktemp)
 	CMDLIST(mv)
+	CMDLIST(cp)
 #if !_std_malloc && !_AST_std_malloc
 	CMDLIST(vmstate)  /* vmstate only works with vmalloc */
 #endif
diff --git a/src/cmd/ksh93/tests/builtins.sh b/src/cmd/ksh93/tests/builtins.sh
index 7444c4324..4e21e6fb3 100755
--- a/src/cmd/ksh93/tests/builtins.sh
+++ b/src/cmd/ksh93/tests/builtins.sh
@@ -1649,5 +1649,41 @@ EOF
 "$SHELL" "$read_a_test"
 let Errors+=$?
 
+# ======
+# The cp builtin's -r/-R flag should not interfere with the -L and -P flags
+if builtin cp 2> /dev/null; then
+	echo 'test file' > "$tmp/cp_testfile"
+	ln -s "$tmp/cp_testfile" "$tmp/symlink1"
+	cp -r "$tmp/symlink1" "$tmp/symlink2"
+	{ test -f "$tmp/symlink2" && test -L "$tmp/symlink2"; } || err_exit "default behavior of 'cp -r' doesn't preserve symlinks"
+	rm "$tmp/symlink2"
+	cp -R "$tmp/symlink1" "$tmp/symlink2"
+	{ test -f "$tmp/symlink2" && test -L "$tmp/symlink2"; } || err_exit "default behavior of 'cp -R' doesn't preserve symlinks"
+	rm "$tmp/symlink2"
+	cp -Pr "$tmp/symlink1" "$tmp/symlink2"
+	{ test -f "$tmp/symlink2" && test -L "$tmp/symlink2"; } || err_exit "'cp -Pr' doesn't preserve symlinks"
+	rm "$tmp/symlink2"
+	cp -PR "$tmp/symlink1" "$tmp/symlink2"
+	{ test -f "$tmp/symlink2" && test -L "$tmp/symlink2"; } || err_exit "'cp -PR' doesn't preserve symlinks"
+	rm "$tmp/symlink2"
+	cp -rP "$tmp/symlink1" "$tmp/symlink2"
+	{ test -f "$tmp/symlink2" && test -L "$tmp/symlink2"; } || err_exit "'cp -rP' doesn't preserve symlinks"
+	rm "$tmp/symlink2"
+	cp -RP "$tmp/symlink1" "$tmp/symlink2"
+	{ test -f "$tmp/symlink2" && test -L "$tmp/symlink2"; } || err_exit "'cp -RP' doesn't preserve symlinks"
+	rm "$tmp/symlink2"
+	cp -Lr "$tmp/symlink1" "$tmp/testfile2"
+	{ test -f "$tmp/testfile2" && ! test -L "$tmp/testfile2"; } || err_exit "'cp -Lr' doesn't follow symlinks"
+	rm "$tmp/testfile2"
+	cp -LR "$tmp/symlink1" "$tmp/testfile2"
+	{ test -f "$tmp/testfile2" && ! test -L "$tmp/testfile2"; } || err_exit "'cp -LR' doesn't follow symlinks"
+	rm "$tmp/testfile2"
+	cp -rL "$tmp/symlink1" "$tmp/testfile2"
+	{ test -f "$tmp/testfile2" && ! test -L "$tmp/testfile2"; } || err_exit "'cp -Lr' doesn't follow symlinks"
+	rm "$tmp/testfile2"
+	cp -RL "$tmp/symlink1" "$tmp/testfile2"
+	{ test -f "$tmp/testfile2" && ! test -L "$tmp/testfile2"; } || err_exit "'cp -LR' doesn't follow symlinks"
+fi
+
 # ======
 exit $((Errors<125?Errors:125))
diff --git a/src/lib/libcmd/cp.c b/src/lib/libcmd/cp.c
index 331002542..9393a1237 100644
--- a/src/lib/libcmd/cp.c
+++ b/src/lib/libcmd/cp.c
@@ -806,8 +806,12 @@ b_cp(int argc, register char** argv, Shbltin_t* context)
 			continue;
 		case 'r':
 			state->recursive = 1;
-			if (path_resolve < 0)
-				path_resolve = 0;
+			if (path_resolve < 1)
+			{
+				state->flags &= ~FTS_META;
+				state->flags |= FTS_PHYSICAL;
+				path_resolve = 1;
+			}
 			continue;
 		case 's':
 			state->op = LN;
@@ -847,12 +851,6 @@ b_cp(int argc, register char** argv, Shbltin_t* context)
 			state->flags |= FTS_PHYSICAL;
 			path_resolve = 1;
 			continue;
-		case 'R':
-			state->recursive = 1;
-			state->flags &= ~FTS_META;
-			state->flags |= FTS_PHYSICAL;
-			path_resolve = 1;
-			continue;
 		case 'S':
 			state->suffix = opt_info.arg;
 			continue;
```

**Comment by McDutchie** [comment]
I don't really have time to test the cp -r/-R fix properly at this point but I'm comfortable taking your word for it if you think it's ready. Are you happy to commit this now?

I'm not keen on having many more separate regression test scripts. I'd like to combine the regression tests for the /opt/ast/bin built-ins into one file, like tests/libcmd.sh. I don't think it needs to warn for commands that are not compiled in.

**Comment by JohnoKing** [comment]
The pull request as it currently is should be ready to merge. I haven't been able to break the cp -r/-R fix.

**Pull request merged**
