### PR TITLE
Add shebang

### PR DESCRIPTION
**Pull request by rymrg**
Instructions for building state:
> Then `cd` to the top directory and run: `bin/package make`

A shebang is required for running the shell script.

### CODE REVIEW

**Comment by pghvlaans** [comment]
I don't believe that particular file has ever had a shebang (or at least not in the last ten years). Did the build fail?

**Comment by rymrg** [comment]
Here is the output from running it without the shebang on the system I compiled it on.
```
$ ./bin/package make
Failed to execute process './bin/package'. Reason:
exec: Exec format error
The file './bin/package' is marked as an executable but could not be run by the operating system.
```
Edit:
It is an issue when running with Fish before version 3.3.0, where the existence of a shebang is required.
The restriction was lifted in:
https://github.com/fish-shell/fish-shell/commit/0048730a67a5e70cafce1fb725a4b28001d924ac

**Comment by JohnoKing** [comment]
I'll note that this problem can also be observed when attempting to run `bin/package make` from tcsh:
```
> bin/package make
min_posix=test / -ef / && path=Bad && case $PATH in (Bad) exit 1;; esac && : Command not found.
min_posix: Undefined variable.
```

Adding a shebang to `bin/package` by itself isn't enough, as after one compile the shebang will be removed. That's because the code from `src/cmd/INIT/package.sh` gets copied over (when modifying the package script, both `bin/package` and `src/cmd/INIT/package.sh` must be updated).
Even then, after adding shebangs to both scripts another problem can be observed: the shebang in `bin/package` is duplicated onto line two after a single compile (which likely because of how the license header is handled).

**Comment by rymrg** [comment]
I found the source of the duplicate. The Mamfile checks if the first line in shebang, and if it is, it adds it before the file.
https://github.com/ksh93/ksh/blob/4ec937455617514d5cb12aef4be69e7438a83232/src/cmd/INIT/Mamfile#L110-L113
I think the fix should be to remove this from the Mamfile (since it is no longer automatically generated) and change `src/cmd/INIT/package.sh` to contain the shebang.

What do you think?

**Comment by JohnoKing** [comment]
I've tested the latest change and everything is working fine AFAICT.

**Comment by hyenias** [comment]
How do we know that the hashbang of `#! /bin/sh` or `#!/bin/sh` exists at that location? Just looking at other executable files within the bin directory, I see `#!/usr/bin/env sh` being used which I believe is a better solution. Wonder how fish and tcsh behave with an executable script having an extension of `.sh`? All of these hashbangs have hardcoded pathing to some degree. Is it possible to utilize the SHELL variable if one exists for the hashbang line or is that just a bad idea as the particular shell script requires a POSIX shell and who knows what someone is using for the SHELL interpreter? 

The hard coding of paths is something I have become aware of recently as an issue when attempting to get ksh working on Android 11 using [TERMUX](https://wiki.termux.com/wiki/Differences_from_Linux). Just food for thought to draw your attention to the use of a particular hashbang and its formatting, e.g. #! followed by a space or not then the program.

**Comment by rymrg** [comment]
`$SHELL` can't be used as it points to the current shell which doesn't have to be POSIX compliant (fish, tsch). In addition, I have confirmed that the fish in question does not care if the file ends with `.sh`.

Technically, no path is guaranteed by POSIX and installation is required to find the location with `getconf PATH` and set the header accordingly. In practice, I think, the only paths you can assume are `/bin/sh` and `/usr/bin/env`. If we don't want to assume an hard coded path, we could update the documentation to `sh bin/package make`.

I have never encountered space after `!#`. [Seems like it was never required](https://www.in-ulm.de/%7Emascheck/various/shebang/#blankrequired).

**Comment by hyenias** [comment]
@rymrg Thank you for answering my inquiries.

**Comment by McDutchie** [comment]
A shebang/hashbang path should not actually be required for running a shell script. The system is supposed to run it with the default shell when it finds that execve(3) fails.

Hashbang paths are a BSD invention and the original UNIX didn't have them. They were [strongly opposed at AT&T](https://github.com/ksh93/ksh/blob/4ec937455617514d5cb12aef4be69e7438a83232/src/cmd/ksh93/sh.memo#L3034-L3080). Cygwin required them for a time and they deeply resented it :)

I can reproduce the problem with running bin/package from tcsh, though. Evidently, tcsh forks and tries to run it as a csh script. This is arguably a bug in tcsh, as POSIX sh is the standard Unix shell language and it should be assumed by default. I'm glad to see that fish fixed the same issue.

So the question is, should we be principled and keep things as they are, or be pragmatic and add a #!/bin/sh hashbang path to bin/package for the benefit of users of (t)csh and old versions of fish?

**Comment by hyenias** [comment]
After reading your linked AT&T comments above, I would keep the things the way they are now. Hopefully, the other shells will correct the situation as based on AT&T's comments it would seem that not using a hashbang is a better solution.

Maybe put a note on the wiki for users of (t)csh and older fish about using `sh bin/package make`.

**Pull request closed without merging**
