### PR TITLE
Implement backwards reverse searches

### LINKED ISSUE #444: Suggestion: Implement backwards reverse search for down arrow key
Currently, using the up arrow in ksh will trigger a reverse search based on the current command line input, although the down arrow key does not have any similar functionality. This isn't very intuitive:
```sh
$ git sh<Up Arrow>  # If the best match is 'git show', then it completes to that
$ git show

# Using down arrow doesn't do a backwards reverse search, which causes
# the closest (non-matching) history file entry to be used instead.
$ git show<Down Arrow>
$ grep -r nv_create
```

My suggestion is to implement this functionality so that the arrow keys function more similarly. Additionally, the Page Up and Page Down keys could support this feature as well. Below is an experimental patch that implements this for emacs mode (edit: patch last updated on 08-18-2022):
```diff
diff --git a/src/cmd/ksh93/edit/emacs.c b/src/cmd/ksh93/edit/emacs.c
index 6ccba23bc..3994c7c4b 100644
--- a/src/cmd/ksh93/edit/emacs.c
+++ b/src/cmd/ksh93/edit/emacs.c
@@ -169,6 +169,7 @@ typedef enum
 static void draw(Emacs_t*,Draw_t);
 static int escape(Emacs_t*,genchar*, int);
 static void putstring(Emacs_t*,char*);
+static int dosearch(Emacs_t*,genchar*,int);
 static void search(Emacs_t*,genchar*,int);
 static void setcursor(Emacs_t*,int, int);
 static void show_info(Emacs_t*,const char*);
@@ -1084,35 +1085,14 @@ static int escape(register Emacs_t* ep,register genchar *out,int count)
 			{
 			    case 'A':
 				/* VT220 up arrow */
-#if SHOPT_EDPREDICT
-				if(!ep->ed->hlist && cur>0 && eol==cur && (cur<(SEARCHSIZE-2) || ep->prevdirection == -2))
-#else
-				if(cur>0 && eol==cur && (cur<(SEARCHSIZE-2) || ep->prevdirection == -2))
-#endif /* SHOPT_EDPREDICT */
-				{
-					/* perform a reverse search based on the current command line */
-					if(ep->lastdraw==APPEND)
-					{
-						out[cur] = 0;
-						gencpy((genchar*)lstring+1,out);
-#if SHOPT_MULTIBYTE
-						ed_external((genchar*)lstring+1,lstring+1);
-#endif /* SHOPT_MULTIBYTE */
-						*lstring = '^';
-						ep->prevdirection = -2;
-					}
-					if(*lstring)
-					{
-						ed_ungetchar(ep->ed,'\r');
-						ed_ungetchar(ep->ed,cntl('R'));
-						return(-1);
-					}
-				}
-				*lstring = 0;
+				if(dosearch(ep,out,1))
+					return(-1);
 				ed_ungetchar(ep->ed,cntl('P'));
 				return(-1);
 			    case 'B':
 				/* VT220 down arrow */
+				if(dosearch(ep,out,0))
+					return(-1);
 				ed_ungetchar(ep->ed,cntl('N'));
 				return(-1);
 			    case 'C':
@@ -1208,16 +1188,34 @@ static int escape(register Emacs_t* ep,register genchar *out,int count)
 				ed_ungetchar(ep->ed,ch);
 				ed_ungetchar(ep->ed,i);
 				return(-1);
-			    case '5':  /* Haiku terminal Ctrl-Arrow key */
+			    case '5':
 				ch = ed_getchar(ep->ed,1);
 				switch(ch)
 				{
-				    case 'D': /* Ctrl-Left arrow (go back one word) */
+				    case 'D': /* Haiku terminal Ctrl-Left arrow (go back one word) */
 					ch = 'b';
 					goto backward;
-				    case 'C': /* Ctrl-Right arrow (go forward one word) */
+				    case 'C': /* Haiku terminal Ctrl-Right arrow (go forward one word) */
 					ch = 'f';
 					goto forward;
+				    case '~': /* Page Up (perform reverse search) */
+					if(dosearch(ep,out,1))
+						return(-1);
+					ed_ungetchar(ep->ed,cntl('P'));
+					return(-1);
+				}
+				ed_ungetchar(ep->ed,ch);
+				ed_ungetchar(ep->ed,i);
+				return(-1);
+			    case '6':
+				ch = ed_getchar(ep->ed,1);
+				if(ch == '~')
+				{
+					/* Page Down (perform backwards reverse search) */
+					if(dosearch(ep,out,0))
+						return(-1);
+					ed_ungetchar(ep->ed,cntl('N'));
+					return(-1);
 				}
 				ed_ungetchar(ep->ed,ch);
 				ed_ungetchar(ep->ed,i);
@@ -1227,7 +1225,8 @@ static int escape(register Emacs_t* ep,register genchar *out,int count)
 				ch = ed_getchar(ep->ed,1);
 				if(ch == '~')
 				{
-					ed_ungetchar(ep->ed,cntl('E')); /* End key */
+					/* End key */
+					ed_ungetchar(ep->ed,cntl('E'));
 					return(-1);
 				}
 				ed_ungetchar(ep->ed,ch);
@@ -1344,6 +1343,50 @@ static void xcommands(register Emacs_t *ep,int count)
 	}
 }
 
+
+/*
+ * Perform a reverse search based on the current command line.
+ * If direction is >0, search forwards in the history.
+ * If direction is <=0, search backwards in the history.
+ *
+ * Returns 1 if the shell did a successful reverse search or
+ * 0 if it couldn't.
+ */
+
+static int dosearch(Emacs_t *ep, genchar *out, int direction)
+{
+#if SHOPT_EDPREDICT
+	if(!ep->ed->hlist && cur>0 && eol==cur && (cur<(SEARCHSIZE-2) || ep->prevdirection == -2))
+#else
+	if(cur>0 && eol==cur && (cur<(SEARCHSIZE-2) || ep->prevdirection == -2))
+#endif /* SHOPT_EDPREDICT */
+	{
+		if(ep->lastdraw==APPEND)
+		{
+			/* Fetch the current command line and save it for later searches */
+			out[cur] = 0;
+			gencpy((genchar*)lstring+1,out);
+#if SHOPT_MULTIBYTE
+			ed_external((genchar*)lstring+1,lstring+1);
+#endif /* SHOPT_MULTIBYTE */
+			*lstring = '^';
+			ep->prevdirection = -2;
+		}
+		if(*lstring)
+		{
+			if(direction<=0)
+				ep->prevdirection = -3;  /* Tell search() to go backwards in history */
+			ed_ungetchar(ep->ed,'\r');
+			ed_ungetchar(ep->ed,cntl('R'));  /* Calls search() */
+			return(1);
+		}
+	}
+	/* Couldn't do a reverse search */
+	*lstring = 0;
+	return(0);
+}
+
+
 static void search(Emacs_t* ep,genchar *out,int direction)
 {
 #ifndef ESH_NFIRST
@@ -1354,6 +1397,7 @@ static void search(Emacs_t* ep,genchar *out,int direction)
 	register genchar *string = drawbuff;
 	/* save current line */
 	int sav_cur = cur;
+	int backwards_search = ep->prevdirection == -3;
 	genncpy(str_buff,string,sizeof(str_buff)/sizeof(*str_buff));
 	string[0] = '^';
 	string[1] = 'R';
@@ -1412,6 +1456,8 @@ static void search(Emacs_t* ep,genchar *out,int direction)
 	}
 	skip:
 	i = genlen(string);
+	if(backwards_search)
+		ep->prevdirection = -2;
 	if(ep->prevdirection == -2 && i!=2 || direction!=1)
 		ep->prevdirection = -1;
 	if (direction < 1)
@@ -1432,7 +1478,7 @@ static void search(Emacs_t* ep,genchar *out,int direction)
 	}
 	else
 		direction = ep->prevdirection ;
-	location = hist_find(sh.hist_ptr,(char*)lstring,hline,1,direction);
+	location = hist_find(sh.hist_ptr,(char*)lstring,hline,1,backwards_search ? -direction : direction);
 	i = location.hist_command;
 	if(i>0)
 	{
```

### PR DESCRIPTION
**Pull request by JohnoKing**
This commit implements the ability to do a backwards reverse search when using the down arrow key in the emacs and vi editing modes. It also implements the ability to do reverse searches with the Page Up and Page Down keys. Previously the only arrow key that performed reverse searches was the up arrow, which could result in confusing behavior:
```sh
$ test foo
$ false
$ test bar
$ te # <Up Arrow * 2> <Down Arrow>
$ false
```
In the above example, using the down arrow after using the up arrow twice results in ksh returning `false` rather than `test bar`. This makes no sense, as you would expect both arrow keys to either perform a reverse search or no reverse search.

src/cmd/ksh93/edit/{emacs,vi}.c:
- Move code for preparing a reverse search to a `dosearch()` function that is called for arrow key reverse searches.
- In emacs mode, perform a backwards reverse search if `ep->prevdirection` is set to -3. This allows `search()` to tell `hist_find()` to search backwards in the history file.
- In vi mode, backwards reverse searches were already available with 'N', so set the mode to 'N' in `dosearch()` when performing backwards reverse searches.
- Add support for performing reverse searches to the Page Up and Page Down keys (this is similar to how mksh handles these keys, though not identical). In emacs mode this allows backwards reverse searches to be performed after using ^R to search.
- vi mode fix: Reverse searches should be canceled after an interrupt (^C) is received. To fix this issue, `vp->direction` is set to -1 in `dosearch()` to cancel the reverse search (a value of -2 is used to indicate an active reverse search). Reproducer for the fixed bug:
```sh
$ test bar=foo
$ sleep 0
$ test foo=bar
$ sleep 0.0
$ te # <Up Arrow*2> + <Ctrl+C) $ <Up Arrow*3>
# The result should be 'sleep 0', but it's actually 'test bar=foo'
```

src/cmd/ksh93/tests/pty.sh:
- Added four regression tests for reverse searching with the arrow keys. Three of these tests are applicable to this commit, while one of them is a regression test for an emacs mode bug that was fixed in commit b5e52703.

Resolves: https://github.com/ksh93/ksh/issues/444

### CODE REVIEW

**Comment by JohnoKing** [comment]
Since this pull request is likely going to be limited to version 1.1, I've separated the bugfix parts into a patch for the 1.0 branch (apply with `git am`):

<details open>
<summary>0001-vi-mode-fix-Cancel-reverse-searches-after-receiving-.patch</summary>

```
From 00af9c66175f0d7a2c8287f694bd4bf9be6aa7cd Mon Sep 17 00:00:00 2001
From: Johnothan King <johnothanking@protonmail.com>
Date: Sat, 10 Sep 2022 13:54:03 -0700
Subject: vi mode fix: Cancel reverse searches after receiving ^C

- Stop a reverse search after an interrupt (^C) is received. Reproducer
  for the fixed bug:
     $ test bar=foo
     $ sleep 0
     $ test foo=bar
     $ sleep 0.0
     $ te <Up Arrow*2> + <Ctrl+C)
     $ <Up Arrow*3>  # Should be 'sleep 0', is actually 'test bar=foo'
  In the above example, the reverse search is still active, so using
  the up arrow key will result in a reverse search. To fix this issue,
  vp->direction is set to -1 in dosearch() to cancel the reverse search
  (a value of -2 is used to indicate an active reverse search).
- Add a regression test for the fixed bug. Additionally, add a
  regression test for an emacs mode reverse search bug that was fixed in
  commit b5e52703.
---
 NEWS                            |  5 +++++
 src/cmd/ksh93/edit/vi.c         |  3 +++
 src/cmd/ksh93/include/version.h |  2 +-
 src/cmd/ksh93/tests/pty.sh      | 35 +++++++++++++++++++++++++++++++++
 4 files changed, 44 insertions(+), 1 deletion(-)

diff --git a/NEWS b/NEWS
index d2f40fa7f..f3f75edfe 100644
--- a/NEWS
+++ b/NEWS
@@ -2,6 +2,11 @@ This documents significant changes in the 1.0 branch of ksh 93u+m.
 For full details, see the git log at: https://github.com/ksh93/ksh/tree/1.0
 Uppercase BUG_* IDs are shell bug IDs as used by the Modernish shell library.
 
+2022-09-10:
+
+- Fixed a bug in vi mode that caused reverse search to remain active after
+  receiving an interrupt.
+
 2022-08-30:
 
 - In the vi line editor, 'C' and 'c$' at the start of a line now enter insert
diff --git a/src/cmd/ksh93/edit/vi.c b/src/cmd/ksh93/edit/vi.c
index 6b521afdd..51933aebd 100644
--- a/src/cmd/ksh93/edit/vi.c
+++ b/src/cmd/ksh93/edit/vi.c
@@ -1670,7 +1670,10 @@ static int mvcursor(register Vi_t* vp,register int motion)
 			else if(cur_virt==0 && vp->direction == -2)
 				ed_ungetchar(vp->ed,'n');
 			else
+			{
+				vp->direction = -1;  /* cancel active reverse search if necessary */
 				ed_ungetchar(vp->ed,'k');
+			}
 			return(1);
 		    case 'B':
 			/* VT220 down arrow */
diff --git a/src/cmd/ksh93/include/version.h b/src/cmd/ksh93/include/version.h
index 8a9e1771d..d551e8010 100644
--- a/src/cmd/ksh93/include/version.h
+++ b/src/cmd/ksh93/include/version.h
@@ -18,7 +18,7 @@
 
 #define SH_RELEASE_FORK	"93u+m"		/* only change if you develop a new ksh93 fork */
 #define SH_RELEASE_SVER	"1.0.4-alpha"	/* semantic version number: https://semver.org */
-#define SH_RELEASE_DATE	"2022-08-30"	/* must be in this format for $((.sh.version)) */
+#define SH_RELEASE_DATE	"2022-09-10"	/* must be in this format for $((.sh.version)) */
 #define SH_RELEASE_CPYR	"(c) 2020-2022 Contributors to ksh " SH_RELEASE_FORK
 
 /* Scripts sometimes field-split ${.sh.version}, so don't change amount of whitespace. */
diff --git a/src/cmd/ksh93/tests/pty.sh b/src/cmd/ksh93/tests/pty.sh
index 0c0bc2edd..d21e6b123 100755
--- a/src/cmd/ksh93/tests/pty.sh
+++ b/src/cmd/ksh93/tests/pty.sh
@@ -1045,5 +1045,40 @@ w echo @ !non_existent
 u @ !non_existent\r\n$
 !
 
+((SHOPT_VSH)) && tst $LINENO <<"!"
+L reverse search isn't canceled after an interrupt in vi mode
+
+d 15
+p :test-1:
+w echo WRONG
+p :test-2:
+w print CORREC
+p :test-3:
+w echo foo
+p :test-4:
+w sleep 0
+p :test-5:
+c e\E[A\E[A\cC\E[A\E[A\E[A
+w $aT
+u CORRECT
+!
+
+((SHOPT_ESH)) && VISUAL=emacs tst $LINENO <<"!"
+L failure to start new reverse search in emacs mode
+# https://github.com/ksh93/ksh/commit/b5e52703
+
+d 15
+p :test-1:
+w echo WRON
+p :test-2:
+w print CORREC
+p :test-3:
+w e\E[AG
+u WRONG
+p :test-4:
+w p\E[AT
+u CORRECT
+!
+
 # ======
 exit $((Errors<125?Errors:125))
-- 
2.37.3


```

</details>

**Comment by McDutchie** [comment]
I've committed your [vi.c bugfix](https://github.com/ksh93/ksh/pull/534#issuecomment-1242804725) to both branches. I'd like to take some more time to consider the rest. I've tested the PR and I find the way the up and down cursor keys now work really awkward -- once you've started a search there seems to be no way out of it except by restarting the command line from scratch. I really, really prefer the way mksh does this -- PgUp/PgDn search, and the arrow keys do not. That is much more consistent with other shells as well.

**Comment by posguy99** [comment]
Many terminal emulators capture PgUp/PgDn before the shell sees them, though.  Wasn't line input changed (I forget the commit) such that backspace would reset the search mode?

Myself, I wish that ksh changed the shell input line like bash does to tell you a search is going on.

**Comment by JohnoKing** [comment]
Perhaps having the arrows keys perform a reverse search can be placed behind an option. I have pushed a commit that implements this in the form of an `arrowkeysearch` option. When it is off (the current default), the arrow keys will not do reverse searches. The PgUp/PgDn keys are not affected by the new option.

**Comment by McDutchie** [comment]
Sorry for taking so long over this. Looks good to me! The shell option is a nice idea. But I think it should be on by default to avoid a too-radical change.

**Pull request merged**
