### PR TITLE
Prevent other ksh93 sessions from interfering with the full editor

### PR DESCRIPTION
**Pull request by pghvlaans**
In both line editors, it is possible to run the full editor on an unexpected command if more than one shell session is running simultaneously. To reproduce:

* Open two `ksh` sessions
* In one session, enter any command or comment.
* In the other session, without reaching a new line or using history navigation, attempt the full editor command.

The command entered in the first session will appear in the editor window rather than the contents of the command line in the second session. This happens because the history line in the second session is overwritten by the first session. Annoyance aside, the behavior could also easily result in an unexpected command being run (if, on seeing unexpected output, the user instinctively quits the editor without saving, for example). 

* {emacs,vi}.c: In case another shell session has used the current history line, when on the last history line, use `hist_eof` and adjust the maximum line and current line before calling `ed_fulledit`. In addition, use `hist_flush` before `ed_fulledit` if the history line is at least as high as `histsize`.

### CODE REVIEW

**Comment by McDutchie** [comment]
Good catch.

Not sure how we'd write a regression test for this one…

**Comment by pghvlaans** [comment]
I was thinking about that, but nothing really suggested itself. Maybe code comments would be good enough in this case?

**Comment by McDutchie** [comment]
On a related note, this full-editor command seems to be undocumented for emacs. At least I cannot find a mention of ^X^E anywhere in the man page.

**Comment by posguy99** [comment]
I'm probably stupid and my comment to the change is there, but I just can't see it.  So I'll add it to the conversation instead.

I applaud documenting ^X^E (only ^X^X is currently documented, there are others), but I don't think it should say THAT. Ref https://github.com/ksh93/ksh/issues/563

You're describing the how there, not the what.

Maybe more like this (cribbed from bash)

       ^X^E
              Invoke an editor on the current command line, and execute the result as shell commands.  Ksh
              attempts to invoke $VISUAL, $EDITOR, and vi  as the editor, in that order.

It should say that execution of the line is attempted when the editor returns, which `mksh` man page makes explicit and `bash` man page more or less says.

**Comment by pghvlaans** [comment]
I just borrowed the line from the vi mode section and made the grammar match. There's a good write-up about editing commands earlier in the page, though, so I went ahead and added a "see also" comment.

**Comment by posguy99** [comment]
There's an inaccuracy here.  That section specifies that all other variables unset leads to it using `ed`, but it doesn't.  It uses `vi`.  The --man information for `hist` also specifies `ed`, so that appears to be wrong too.

**Comment by pghvlaans** [comment]
It uses `ed` if the `-e` option isn't present.

**Comment by posguy99** [comment]
I think the point I was trying to make is that ^X^E never does, since the command line it forces into the buffer specifies -e and falls into `vi` as the last alternative.  So referring to Command Re-Entry is at best confusing.

**Comment by pghvlaans** [comment]
It seems clear enough to me, but I'll think about it again later.

**Comment by pghvlaans** [comment]
I'm going to edit `sh.1` in PR #659 instead because it deals with `^X^E` more directly.

**Comment by hyenias** [comment]
Here are my thoughts on how to create a regression test for the CTRL+x then CTRL+e external full editor. Trying to launch an actual editor such as vi, nano, emacs, etc. is too difficult, why not create an external program to perform the resulting steps an external editor would take?

Maybe a small C program. Maybe just a POSIX shell script. Just need to accept some input, verify that input, write out something, then the ksh program can verify that something. Basically, VISUAL/EDITOR=dummy_test_editor_external_program.

Below, I typed in `sleep 2` then CTRL+x,CTRL+e which launched nano as my editor in which I added the line `echo hello back`, then exited saving to buffer.

```
$ \hist -e "${VISUAL:-${EDITOR:-vi}}" 943
sleep 2
echo hello back

hello back
$
```

**Comment by pghvlaans** [comment]
That's an interesting idea, thanks! Calling a separate shell with `ksh -i` and some combination of sleep commands might do the trick.

**Comment by pghvlaans** [comment]
The PR needs a rework, sorry. It fails when history is full.

**Comment by pghvlaans** [comment]
That seems to make the fix work when the history line is at or over the maximum size.

**Comment by McDutchie** [comment]
LGTM!

**Comment by McDutchie** [comment]
I would still welcome a regression test if someone can come up with one, but I don't consider it a high priority. Also it should not be too slow (if we get too many slow tests, I'll get impatient and stop running the regression tests as much, which is bad for everyone ;-)).

**Comment by hlangeveld** [comment]
This used to be major _pain in the butt_ in the past when using ksh93 in `screen`  or `tmux`.

I used to have a workaround, where `.kshrc` would set `HISTFILE` to `~/.history/${ttyname}`

**Comment by posguy99** [comment]
> I used to have a workaround, where `.kshrc` would set `HISTFILE` to `~/.history/${ttyname}`

I always do that.  I usually have at least two shells open and I **want** them to be separated.

**Pull request merged**
