### PR TITLE
typeset -p: short integer undefined value display fix

### PR DESCRIPTION
**Pull request by hyenias**
When issuing `typeset -p` for short integers without a defined value,
a printed value of 0 was displayed. This commit alters the print_value
function to not exclude short integers from being recognized as null
or having an undefined value. It also corrects a memory fault
combination that could occur if -l followed a -s option with integers.
Additionally, now the last -s/l wins out as the option to utilize
instead of it always being short.

src/cmd/ksh93/include/name.h:
Creation of a new macro called 'nv_isundef' that lacks nv_isnull's
direct exclusion of short integers. Altering nv_isnull is too
impactful for this commit. More than likely, the use of short integers
has been severely impacted by nv_isnull's short integer exclusion.

src/cmd/ksh93/bltins/typeset.c:
b_typeset():
- If the long attribute was applied after the short attribute, a
  memory fault happens as the short flags were not reset.

print_value():
- Replace nv_isnull(np) with newly created nv_isundef(np) macro as
  to not exclude short integers from being identified as having an
  undefined value.

src/cmd/ksh93/tests/attributes.sh:
- Add in missing short integer tests and correct the one that existed.
  The -si test now yields 'typeset -x -r -s -i foo' instead of
  'typeset -x -r -s -i foo=0' which brings it inline with all the
  others.
- Add in some other -l attribute tests for floats. Note, -lX test was
  not added as the size of long double is platform dependent.

### CODE REVIEW

**Comment by McDutchie** [comment]
> Altering nv_isnull is too impactful for this commit.

I'd like to corroborate that, and see what actually breaks if we do remove that check for short integer from it. On the face of it, that check doesn't make very much sense for such a general-use macro. If it's just a few things that break, I'd rather add an explicit check for short integer to those cases rather than introduce another macro.

**Comment by hyenias** [comment]
ok

**Comment by McDutchie** [comment]
I had a dive in the multishell repo history.

In the oldest 2002 version, that check [wasn't there](https://github.com/multishell/ksh93/blob/344b054f0c582bcabb9548267490ee05fcf1a8c4/src/cmd/ksh93/include/name.h#L133):
```c
#define nv_isnull(np)  (!(np)->nvalue.cp && !(np)->nvfun)
```

[2004-02-29](https://github.com/multishell/ksh93/blob/beb884a5bcb3387a44486150951ffc8d59f85710/src/cmd/ksh93/include/name.h#L133):
```c
#define nv_isnull(np)  (!(np)->nvalue.cp && !(np)->nvfun && !nv_isattr(np,NV_SHORT))
```

[2008-07-25](https://github.com/multishell/ksh93/blob/8e947ccf8ce2bf1fda57f04e59f4a9a4782cab99/src/cmd/ksh93/include/name.h#L157):
```c
#define nv_isnull(np)  (!(np)->nvalue.cp && !((np)->nvfun && (np)->nvfun->disc) && nv_isattr(np,NV_SHORT|NV_INTEGER)!=(NV_SHORT|NV_INTEGER))
```

[2009-12-24](https://github.com/multishell/ksh93/blob/80b2c8c6cfb15d65226772f1b0047e96648173d9/src/cmd/ksh93/include/name.h#L159-L160) (current version):
```c
#define _nv_hasget(np)  ((np)->nvfun && (np)->nvfun->disc && nv_hasget(np))
#define nv_isnull(np)  (!(np)->nvalue.cp && (nv_isattr(np,NV_SHORT|NV_INTEGER)!=(NV_SHORT|NV_INTEGER)) && !_nv_hasget(np))
```

**Comment by hyenias** [comment]
It did not make sense to me seeing it in the macro. I kept overlooking the nv_isnull() macro as what was causing a short integer to have a value in print_value().

Oh, apparently we need more "stars" than our parent repo before we can use it for searching. :( I will need to get setup for such an endeavor and investigation work. Just to set your expectations, with my time allotment, it will take me many days to reach the final goal.

**Comment by McDutchie** [comment]
When I remove the `&& (nv_isattr(np,NV_SHORT|NV_INTEGER)!=(NV_SHORT|NV_INTEGER))` bit from the `nv_isnull()` macro, not very many regressions are detected by bin/shtests. Below are all of them. The first one is actually a fix, of course. So this might be worth looking into. The code would make more sense if we just add that `NV_SHORT|NV_INTEGER` check explicitly in the places that actually need it.

```
	attributes.sh[551]: unset exported readonly with -si: expected 'typeset -x -r -s -i foo=0', got 'typeset -x -r -s -i foo'
	basic.sh[753]: DEBUG trap inherited by ksh function (expected $'Debug 0\nFunctionEnv\nDebug 0\nParentEnv', got $'Debug\nFunctionEnv\nDebug\nParentEnv')
	basic.sh[768]: DEBUG trap not inherited by POSIX function (expected $'Debug 0\nDebug 1\nFunction\nDebug 0\nNofunction', got $'Debug\nDebug 1\nFunction\nDebug\nNofunction')
	leaks.sh[165]: unset of associative array causes memory leak (leaked approx 132 KiB after 16384 iterations)
	variables.sh[698]: ${.sh.subshell} should be 0
```

**Comment by McDutchie** [comment]
> Oh, apparently we need more "stars" than our parent repo before we can use it for searching. :( I will need to get setup for such an endeavor and investigation work.

I'm not quite sure what you're talking about, re "stars". To find all the changes (*edit:* I mean, all the historic changes to the `nv_isnull()` macro), I cloned the [multishell ksh93 repo](https://github.com/multishell/ksh93/) locally, did `git log -p --reverse src/cmd/ksh93/include/name.h`, and used my pager to search for `#define nv_isnull`.

**Comment by McDutchie** [comment]
It seems like all the actual regressions except the leak can be explained by the fact that `${.sh.subshell}` and `${.sh.level}` stop working after the `nv_isnull()` change.

**Comment by JohnoKing** [comment]
Alternatively, to search for all instances of `nv_isnull` in 93u+m you could run `grep -r 'nv_isnull' ./src` at the root of the repository.

**Comment by McDutchie** [comment]
Well yes. I do a *lot* of recursive grepping. That doesn't search the history though.

**Comment by McDutchie** [comment]
Something else occurred to me. Since the fix for #157 uses `nv_isnull()`, that is probably still broken for short integers.

Sure enough:
```
$ arch/*/bin/ksh -c 'typeset -si a b=42; echo ${a:=b}; echo $a'   
0
0
```
(expected: `42`, twice)

This confirms for me that we really need to fix `nv_isnull()`.

**Comment by McDutchie** [comment]
The leaks.sh [regression](https://github.com/ksh93/ksh/pull/211#issuecomment-792333671) may have been a false alarm, as I cannot reproduce it now, with or without a fixed `nv_isnull()` macro. I do very occasionally get false positives in leaks.sh as `ps`(1) on macOS tends to behave in a rather non-deterministic manner for some reason.

So that means that every regression caused by this change is because `${.sh.subshell}` and `${.sh.level}` stop yielding a value. Which means they added this general check to this general-use macro just to get that one very specific thing working, apparently not considering or noticing that other stuff might break.

Is this the sort of hare-brained design decision that I've come to expect from AT&T? Yes. Yes, it is.

So, it looks like we just need to find out where or how to special-case `${.sh.subshell}` and `${.sh.level}`, and then we can fix `nv_isnull()` and be done with it.

**Comment by McDutchie** [comment]
I've managed to fix `${.sh.subshell}` to work with the fixed `nv_isnull()` macro without any special-casing, by changing how the value of that variable is stored to match the method used for `${.sh.pid}`. To understand what's going on, we first need to understand the `Value` union from name.h: https://github.com/ksh93/ksh/blob/40860dac20b02b5b471fb3c22cd543735123eb10/src/cmd/ksh93/include/name.h#L36-L57

A union is like a struct, except all its members occupy the same memory space, so only one of its members can be used at a time. This allows assigning different types of values. Each `Namval_t` name-value struct has an `nvalue` member that is of type `union Value`.

The reason `${.sh.subshell}` didn't work with the `nv_isnull()` macro, which checks for the `cp` union member (a pointer), is that it assigns a value of type `int16_t` (the `s` union member) directly: https://github.com/ksh93/ksh/blob/40860dac20b02b5b471fb3c22cd543735123eb10/src/cmd/ksh93/sh/subshell.c#L540

Whereas `${.sh.pid}` works by assigning a pointer to an `int32_t` value once (the `lp` union member), then is never changed again; that `int32_t` value it points to is changed instead. So `nv_isnull()` checks for the character pointer `cp`, and since all pointers are equivalent in C for determining a null or non-null value, that will work. https://github.com/ksh93/ksh/blob/40860dac20b02b5b471fb3c22cd543735123eb10/src/cmd/ksh93/sh/init.c#L1859

The following commit changes `${.sh.subshell}` to work like `${.sh.pid}` in this sense. `${.sh.level}` (`SH_LEVELNOD`) is a lot more complicated, I don't understand all the voodoo going on with that yet; it is treated very differently and also special-cased in `sh_assignok()`. I may look into that later. For now, it seems to work to special-case it in macro.c, at the same place where the fix for #157 was applied.

While we're at it, we can also add a `pid_t*` pointer member `pidp` to the `Value` union, as `$PPID` and `${.sh.pid}` are actually values of type `pid_t` and referring to them using `int32_t` pointers does not seem technically correct. Those might be the same width on most systems, but I don't think it's guaranteed.

With those changes and a fixed `nv_isnull()` macro, I get no regression test failures. Instead of posting a patch here, I'll just add a commit to this PR. It should be linked directly below this comment. Please test. You can `git fetch origin pull/211/head && git checkout FETCH_HEAD` to temporarily use this PR's current code (then `git checkout master` to switch back).

**Comment by hyenias** [comment]
I am a fledgling programmer. So, I really do appreciate all the pointers and programming directions as programming in C is challenging to me especially with this code base. And, I truly believe ksh93 is the best! By making my little contributions here-and-there, I am pleased that through the massive help from others, ksh93 continues to survive and soon will shine like it has never shined before.

My reference to needing more stars than the upstream parent repo is found here: [Searching in forks](https://docs.github.com/en/github/searching-for-information-on-github/searching-in-forks). I initially tried the web browser to find the occurrences `ns_isnull`. That failed.

@JohnoKing, thanks for the insight into using grep to search my local branch directory. @McDutchie, also thanks for your advanced insights but introducing my eyes/mind to history info is too much for me to handle. I will concentrate on the actual files that I am changing as I am still very new and I do not posses that level of skill to effectively use it at this time.

I got all sorts of learning to do with this pull request. @McDutchie, thank you for leadership and correcting the code changes to resolve so much more than I am capable of doing at this moment.

I so much **LIKE** the git branch shortint-print_value updates than having to mess around with the embedded diffs. I understand that embedded diffs are a nice tool for comment discussions and such.

Now to go do some more fun stuff...

**Comment by McDutchie** [comment]
I didn't mean to make some deep or mysterious point with the historic info on the `nv_isnull()` macro definition, it's just that this shows the bizarre exception for short ints that broke stuff wasn't always there.

It's a pattern I've found: breakage is often introduced in later ksh versions by some change that reveals itself to be obviously silly when you think about it logically, like "let's consider all the short int variables as set, whether they are or not", and such nonsense can be fixed by reverting it, and fixing whatever breaks in a sensible way instead. Which is what I tried to do with the added commit. The recent fixes for the `DEBUG` trap are another good example of this (#155), as is the recently fixed vulnerability with array subscripts (#152).

I'm not an advanced C programmer myself, although I think my C skills probably increased since I started in earnest on this project in May last year...

**Comment by hyenias** [comment]
All tested by hand with all my notes. All good.

FYI, here are the git commands I used to update my local git branch that I used to create the PR and pull down your updates:
```
$ git checkout shortint-print_value
Switched to branch 'shortint-print_value'
$ git status
On branch shortint-print_value
nothing to commit, working tree clean
$
$ git pull origin shortint-print_value
From https://github.com/hyenias/ksh93
 * branch            shortint-print_value -> FETCH_HEAD
Updating 46417ae..54ae28f
Fast-forward
 src/cmd/ksh93/bltins/typeset.c   |  2 +-
 src/cmd/ksh93/data/variables.c   |  2 +-
 src/cmd/ksh93/include/defs.h     |  1 +
 src/cmd/ksh93/include/name.h     |  4 ++--
 src/cmd/ksh93/sh/init.c          |  5 +++--
 src/cmd/ksh93/sh/macro.c         |  2 +-
 src/cmd/ksh93/sh/subshell.c      |  6 +++---
 src/cmd/ksh93/sh/xec.c           |  2 +-
 src/cmd/ksh93/tests/variables.sh | 15 +++++++++++++++
 9 files changed, 28 insertions(+), 11 deletions(-)
$
```

**Comment by McDutchie** [comment]
Alright then, let's merge this and see what happens.

**Comment by JohnoKing** [comment]
I might as well add that in ksh93v- `nv_isnull` was turned into a function:
https://github.com/att/ast/blob/e770c77e9816e156c6df4a455e71b5f9fff79310/src/cmd/ksh93/sh/name.c#L3962-L3973

It ended up breaking `${.sh.subshell}` when that variable was used in the `$PS4` prompt: https://github.com/att/ast/issues/1092.

**Comment by McDutchie** [comment]
Whereas running `unset .sh.subshell` and then accessing it from a subshell causes a segfault on every ksh93 version (93v- and 2020 included) except 93u+m after this fix.
```
$ /bin/ksh -c 'echo ${.sh.version}; unset .sh.subshell; (echo ${.sh.subshell}); echo end'
Version AJM 93u+ 2012-08-01
Memory fault
$ arch/*/bin/ksh -c 'echo ${.sh.version}; unset .sh.subshell; (echo ${.sh.subshell}); echo end'
Version AJM 93u+m/1.0.0-alpha+dev 2021-03-13

end
```
The variable loses its special meaning after unsetting, but that is fine.

**Comment by JohnoKing** [comment]
> Whereas running `unset .sh.subshell` and then accessing it from a subshell causes a segfault on every ksh93 version (93v- and 2020 included) except 93u+m after this fix.

Not quite. It works without crashing in ksh93r. `${.sh.subshell}` also keeps its special meaning in that version:
```
$ ksh2006 --version
  version         sh (AT&T Labs Research) 1993-12-28 r
$ unset .sh.subshell; (echo ${.sh.subshell})
1
```

**Pull request merged**
