### PR TITLE
Editing mode fixes

### PR DESCRIPTION
**Pull request by pghvlaans**
EDIT: Please see [this comment](https://github.com/ksh93/ksh/pull/565#issuecomment-1293757822) below for an updated description.

In `vi` mode, calling `v` from an empty line fails to bring up the full editor. The root cause is probably a bad interaction with `hist`: the builtin seems to expect either non-space characters or a new line from position 0 (rather than position -1, or `INVALID` in `vi.c`). Because `emacs` mode always inserts `\n` when calling for the full editor (see `emacs.c:1243`), it does not experience this problem.

* In `vi.c`, ~~advance `lastvirt`~~ set the position to 0, refresh and insert `\n` if command mode `v` is called from an empty line or a line made up entirely of spaces. This allows `hist` to call a full editor with the proper range.

### CODE REVIEW

**Comment by pghvlaans** [comment]
Linux, FreeBSD and NetBSD all look OK, but the patched build is segfaulting on OpenBSD when `v` is attempted from an empty line.

**Comment by pghvlaans** [comment]
In the case of a completely empty line, a better solution (i.e., one that doesn't crash on OpenBSD) is to set the position to 0, refresh, and only then add `\n`. Refreshing is also good for lines of spaces, which would otherwise be partially carried over to true `vi`.

Everything checks out on Linux, FreeBSD, OpenBSD, NetBSD, macOS and illumos.

~~macOS is failing to build at the moment (patched and unpatched), so I'll open an issue about that after attempting with a debugging flag.~~ (Probable user error; see issue #567)

**Comment by pghvlaans** [comment]
This PR addresses three behaviors in `vi` mode and one behavior in `emacs` mode:

* In `vi` mode, calling `v` from a completely empty line rings the bell rather than calling the full editor.
* In `vi` mode, calling `v` from a spaces-only line results in an "invalid range" `hist` error, and the editor fails to open.
* In both modes, navigating to an empty history line displays an empty line onscreen (see #563).

The following fixes are applied:

* The `hist` builtin seems to expect either a new line with the cursor in position `0` or a line with at least one non-space character. In `vi.c`, set the position to `0`, refresh and insert `\n` if command mode `v` is called from an empty line or a line made up entirely of spaces. This allows `hist` to call the full editor with the proper range.
* Other shells, including `mksh`, `oksh`, `bash` and `yash`, also save empty history lines. However, actually displaying these blank lines when navigating using e.g. the arrow keys (as is the case in `ksh`, `mksh` and `oksh`) is unhelpful. In `vi.c` and `emacs.c`, check the history line for non-space characters. If the line is completely empty, resend the appropriate key provided that doing so would not go beyond the confines of the first and last history lines. This effectively skips empty lines when navigating.

**Comment by pghvlaans** [comment]
One last change: the `allempty` loops were starting to be used in too many places across `vi.c` and `emacs.c`, so they were replaced by an `allempty` function in each.

**Comment by posguy99** [comment]
Re empty lines... I get dealing with them if they're there, but how do they get there?  You reference my https://github.com/ksh93/ksh/issues/563 , which is one way for them to get there.

The real answer should be fixing whatever inserts them into the history in the first place, IMO.

**Comment by pghvlaans** [comment]
Comparing `history` output from `vi` mode and `emacs` mode, it appears that the contents of the command line are possibly being saved to the history file without a trailing newline upon `^x^e`.

EDIT: ~~This is definitely what's happening. `vim` as `VISUAL` shows a `noeol` message when the full editor is called from `emacs` mode.~~ Actually, `noeol` only shows up when there's already something on the line when `^x^e`.

**Comment by pghvlaans** [comment]
This (somewhat expanded) PR addresses three behaviors in `vi` mode and two behaviors in `emacs` mode:

* In `vi` mode, calling `v` from a completely empty line rings the bell rather than calling the full editor.
* In `vi` mode, calling `v` from a spaces-only line results in an "invalid range" `hist` error, and the editor fails to open.
* In `emacs` mode, calling the full editor saves the current contents of the command line to the history file without a new line ([Issue #563](https://github.com/ksh93/ksh/issues/563#issue-1418653720)).
* In both editing modes, navigating to a null or empty history line displays an empty line onscreen.

A summary of the fixes:

The `hist` builtin seems to expect either a new line with the cursor in position `0` or a line with at least one non-space character; in all cases, the line should conclude with `\n` and `\0`:
* In `vi.c`, set the position to `0`, refresh and insert `\n` if command mode `v` is called from an empty line or a line made up entirely of spaces. This enables `hist` to call the full editor with an appropriate range.
* In `emacs.c`, add `\n` and `\0` to `drawbuff` before calling `ed_fulledit` (but after checking its failure conditions). This prevents the insertion of `null` history items for both empty and non-empty lines. Because lines composed entirely of spaces can cause the following prompt to be offset, clear such lines as well.

Other shells, including `mksh`, `oksh`, `bash` and `yash`, also save empty history lines. However, actually displaying these blank lines when navigating using e.g. the arrow keys (as is the case in `ksh`, `mksh` and `oksh`) is unhelpful:
* In `vi.c` and `emacs.c`, check the history line for non-space characters. If the line is completely empty, resend the appropriate key provided that doing so would not go beyond the confines of the first and last history lines. This effectively skips empty lines when navigating.

**Comment by pghvlaans** [comment]
Another bugfix:

Attempting to tab-complete an alias or `$PATH` item containing wide characters before the first normal-width character has been entered fails in both `vi` and `emacs` modes (see #532). The mechanism for finding empty lines does not recognize wide non-space characters as non-space characters, so lines with nothing but wide characters always fail to reach the completion stage. When `SHOPT_MULTIBYTE`, use `!iswspace` rather than `!isspace` to detect wide characters. (bug introduced by a874586)

**Comment by McDutchie** [comment]
Thank you very much for this PR which fixes multiple bugs!

**Pull request merged**
