### PR TITLE
Fix #447 confusing behaviour of backreferences with alternation

### LINKED ISSUE #447: confusing behaviour of backreferences with alternation
```
$ var='ab' ksh -c 'print -r -- "${var//@(@(a)|b)/<\1+\2>}"'
<a+a><b+\2>
```

I expected:

```
<a+a><b+>
```

These are OK:

```
$ var='a1b2' ksh -c 'print -r -- "${var//@(@(a)|b)@(?)/[1:<\1> 2:<\2> 3:<\3>]}"'
[1:<a> 2:<a> 3:<1>][1:<b> 2:<> 3:<2>]
```
```
$ var='ab' ksh -c 'print -r -- "${var//@(@(a)|@(b))/<\1+\2>}"'
<a+a><b+>
````

Though in that latter one, we have the same problem with `\3`:

```
$ var='ab' ksh -c 'print -r -- "${var//@(@(a)|@(b))/<\1+\2+\3>}"'
<a+a+\3><b++b>
```

### PR DESCRIPTION
**Pull request by phidebian**
The bugs exhibit itself as

    TC$ a=AB ; echo "${a/@(A)/:\0:\1:\2}"  
    :A:A:\2B

The \2 that is a an anchor reference is not part of a replacement string and should not be expansed.

This fix address that.

The QA need tweaking as well, to adapt to the new output...

### CODE REVIEW

**Comment by McDutchie** [comment]
Thank you! This fix seems to work with all of @stephane-chazelas' reproducers from #447 as well.

**Comment by phidebian** [comment]
You welcome :)

**Comment by phidebian** [comment]
Oops I reworded by 'thin' commit message for this one with a more
explanatory one, to discover in fact you did it already :-)

That's a good pedagogic thing, mine was too detailed I think, yours is in
the middle, I keep yours :) it will inspire me for the printf case...

**Comment by McDutchie** [comment]
See `git log` (with full commit messages) for lots more inspiration. :)

BTW, I made a minor mistake when merging -- failed to replace the header line, so now it has a double header line. Oh well.

**Comment by phidebian** [comment]
No biggies, I try to reword the printf %T case commit message, this one is
real tricky, hope my explanations will help. Got other duties right now,
but will try today....

**Pull request merged**
