### PR TITLE
Continous integration builds using Github actions

### PR DESCRIPTION
**Pull request by aweeraman**
This includes a starter Github Actions CI config for Linux and MacOS.

### CODE REVIEW

**Comment by McDutchie** [comment]
Thanks. Is there a way for this to run the regression tests as well? (just `bin/shtests` should do)

**Comment by aweeraman** [comment]
Yes, it will break right now since there are some test failures. I can update this PR with it if you like. Alternatively, we can enable it once all the tests are known to be working so we can spot a failure when something breaks. Either way works.

**Comment by aweeraman** [comment]
@McDutchie, updated PR to enable tests. Builds will show up as failing due to tests in the interim, which is not a bad thing, and will make the eventual successful build all the more fun.

**Comment by McDutchie** [comment]
That's mystifying. I am *not* getting any regression test failures on Ubuntu 16.04.6 LTS.

**Comment by aweeraman** [comment]
Hmm... I'm seeing a few failures such as as this:
```
bracket.sh[374]: /dev/tty: cannot create [No such device or address]
	bracket.sh[376]: test -t 1 in comsub with exec >/dev/tty fails
```
This may be because of the build environment which doesn't appear to have /dev/tty.
On my own Debian laptop, I'm seeing a few test failures such as this:
```
test bracket begins at 2020-06-22+18:22:06
	bracket.sh[243]: test -N $tmp/*: st_mtime>st_atime after read
test bracket failed at 2020-06-22+18:22:07 with exit code 1 [ 120 tests 1 error ]
test bracket(C.UTF-8) begins at 2020-06-22+18:22:07
	bracket.sh[243]: test -N $tmp/*: st_mtime>st_atime after read
test bracket(C.UTF-8) failed at 2020-06-22+18:22:07 with exit code 1 [ 120 tests 1 error ]
test bracket(shcomp) begins at 2020-06-22+18:22:07
	shcomp-bracket.ksh[243]: test -N $tmp/*: st_mtime>st_atime after read
```
and
```
signal.sh: line 466: 2442002: Memory fault
	signal.sh[466]: `kill` doesn't handle a non-existent job correctly when passed '%%'
signal.sh: line 467: 2442003: Memory fault
	signal.sh[467]: `kill` doesn't handle a non-existent job correctly when passed '%+'
signal.sh: line 468: 2442004: Memory fault
	signal.sh[468]: `kill` doesn't handle a non-existent job correctly when passed '%-'
test signal failed at 2020-06-22+18:24:08 with exit code 3 [ 48 tests 3 errors ]
test signal(C.UTF-8) begins at 2020-06-22+18:24:08
signal.sh: line 466: 2442196: Memory fault
	signal.sh[466]: `kill` doesn't handle a non-existent job correctly when passed '%%'
signal.sh: line 467: 2442197: Memory fault
	signal.sh[467]: `kill` doesn't handle a non-existent job correctly when passed '%+'
signal.sh: line 468: 2442198: Memory fault
	signal.sh[468]: `kill` doesn't handle a non-existent job correctly when passed '%-'
test signal(C.UTF-8) failed at 2020-06-22+18:24:17 with exit code 3 [ 48 tests 3 errors ]
test signal(shcomp) begins at 2020-06-22+18:24:17
/tmp/ksh93.shtests.2416179.2216/shcomp-signal.ksh: line 466: 2442410: Memory fault
	shcomp-signal.ksh[466]: `kill` doesn't handle a non-existent job correctly when passed '%%'
/tmp/ksh93.shtests.2416179.2216/shcomp-signal.ksh: line 467: 2442411: Memory fault
	shcomp-signal.ksh[467]: `kill` doesn't handle a non-existent job correctly when passed '%+'
/tmp/ksh93.shtests.2416179.2216/shcomp-signal.ksh: line 468: 2442412: Memory fault
	shcomp-signal.ksh[468]: `kill` doesn't handle a non-existent job correctly when passed '%-'
```

**Comment by aweeraman** [comment]
You can see them here: https://github.com/aweeraman/ksh93/runs/797150983?check_suite_focus=true

**Comment by JohnoKing** [comment]
On both of my Linux systems (but not on my FreeBSD laptop) I get the following failure in the `pty` test:
```
test pty begins at 2020-06-22+15:27:27
	pty.sh[438]: process/terminal group exercise: line 444: expected "Stopped", got ""
test pty failed at 2020-06-22+15:27:39 with exit code 1 [ 21 tests 1 error ]
test pty(C.UTF-8) begins at 2020-06-22+15:27:39
	pty.sh[438]: process/terminal group exercise: line 444: expected "Stopped", got ""
test pty(C.UTF-8) failed at 2020-06-22+15:27:50 with exit code 1 [ 21 tests 1 error ]
test pty(shcomp) begins at 2020-06-22+15:27:50
	shcomp-pty.ksh[438]: process/terminal group exercise: line 444: expected "Stopped", got ""
test pty(shcomp) failed at 2020-06-22+15:28:02 with exit code 1 [ 21 tests 1 error ]
```

I also get a test failure for `printf %T now` on my laptop with Ubuntu 20.04, but not on my desktop with Arch Linux. I have submitted a pull request to fix that one (#38).

**Comment by JohnoKing** [comment]
The test failure @aweeraman was getting in the bracket test can be replicated by mounting /tmp with the `noatime` option:
```
# mount -o remount,rw,noatime /tmp
```

**Comment by McDutchie** [comment]
@aweeraman, I think the `kill` failures probably happened because you forgot to recompile after ff358f3464bce5a2ec18e642cf5886afc5259f9e.

**Comment by McDutchie** [comment]
Anyway, let's merge this and see what happens. I've no experience with this whole newfangled continuous integration business, but now is as good a time as any to gain some… :)

**Comment by aweeraman** [comment]
@McDutchie, I'm not getting the kill failures now after getting the latest updates. 6 tests still failing though locally on my laptop, will look into what @JohnoKing suggested, that should resolve the bracket test failures.

```
test bracket failed at 2020-06-22+18:55:32 with exit code 1 [ 120 tests 1 error ]
test bracket(C.UTF-8) failed at 2020-06-22+18:55:32 with exit code 1 [ 120 tests 1 error ]
test bracket(shcomp) failed at 2020-06-22+18:55:33 with exit code 1 [ 120 tests 1 error ]
test pty failed at 2020-06-22+18:56:45 with exit code 1 [ 21 tests 1 error ]
test pty(C.UTF-8) failed at 2020-06-22+18:56:57 with exit code 1 [ 21 tests 1 error ]
test pty(shcomp) failed at 2020-06-22+18:57:09 with exit code 1 [ 21 tests 1 error ]
```

**Comment by McDutchie** [comment]
@aweeraman – So, the Github-provided Ubuntu test build environment is a bit broken and limited.

As observed, it doesn't have `/dev/tty` which is one of the very few paths that POSIX actually specifies. That can be worked around by skipping the tests that require it.

But I don't think we can do anything about the "open file limit exceeded" in the test below. That just inherently requires a lot of open files. It passes just fine on a standard Ubuntu system. https://github.com/ksh93/ksh/blob/c1994b87f19995fcc52079322ac6e26cde70d4be/src/cmd/ksh93/tests/subshell.sh#L247-L269

So what to do about that then? Does GitHub provide other Linux test build environments for CI?

**Comment by aweeraman** [comment]
@McDutchie, let me investigate this a little. I think it might be possible to increase the file limits through ulimit, let me try and see if we can get it to go through. On /dev/tty, there might be some workarounds. Will get back.

In the meantime, I see a couple of Mac builds hung right now, possibly due to resource contention. The last build seems to have gone through to completion. Could you cancel the other two builds? They're just spinning right now.

**Comment by McDutchie** [comment]
I've cancelled the hung builds.

I don't trust the Mac regression test failures at all. Their Mac environment doesn't seem to have `/dev/tty` either and that is definitely bogus. None of the other failures happen on a real Mac either (e.g. SIGCHLD doesn't work? what?). So far I'm not impressed with how this is going.

**Pull request merged**
